#ifndef _LANG_VIEWER_H_
#define _LANG_VIEWER_H_

#include "Include/Language.h"

//language resource 
 
#define		ID_STR_OK							10001	//ȷ��
#define		ID_STR_EXIT							10002	//�˳�
#define		ID_STR_CANCEL						10003	//ȡ��
#define		ID_STR_CHANNEL						10004	//ͨ��
#define		ID_STR_TITLE						10005	//CMS Client
#define		ID_STR_MAP							10006	//��ͼ����
#define		ID_STR_VIEW							10007	//��Ƶ����
#define		ID_STR_VIEW_MAP						10008	//��Ƶ\��ͼ
#define		ID_STR_NAVIGATE						10009	//�������
#define		ID_STR_SAVE_SUC						10010	//����ɹ�
#define		ID_STR_EVENT						10011	//�¼����
#define		ID_STR_CONFIRM_DELETE				10012	//����ɾ���󽫲��ɻָ����Ƿ�ɾ����
#define		ID_STR_SELECT_FOLDER				10013	//ѡ��·��
#define		ID_STR_CAR_CENTER					10014	//�Գ���Ϊ����
#define		ID_STR_SELECT_DEVICE				10015	//ѡ����
#define		ID_STR_SNAPSHOT						10016	//ץ��ͼƬ
#define		ID_STR_VOLUME						10017	//��������
#define		ID_STR_SELECT_DEV_EMPTY				10018	//��ѡ��һ��������㣬���߳���ͨ����㣡
#define		ID_STR_PANE_PLAY					10019	//�������
#define		ID_STR_VIEW_POP						10020	//������Ƶ����
#define		ID_STR_VIEW_TITLE					10021	//��Ƶ����
#define		ID_STR_READY						10022	//����
#define		ID_STR_MAP_VIEW						10023	//��ͼ\��Ƶ
#define		ID_STR_PANE_TRACK					10024	//�������
#define     ID_STR_MONITOR                      10025   //���
#define     ID_STR_STATISTIC                    10026   //ͳ��
#define     ID_STR_CMS_LOGINPASSWORD            10027   //(CMS��¼����)
#define		ID_STR_YES							10028	//��
#define		ID_STR_NO							10029	//��
#define		ID_STR_ADD_SUCCESS					10030	//���ӳɹ�
#define		ID_STR_DEL_SUCCESS					10031	//ɾ���ɹ�
#define		ID_STR_SAVING						10032	//���ڱ���...
#define		ID_STR_SNAPSHOT_MENU				10033	//ץ��

#define		ID_STR_PRIVILIDEG_USR_MGR			10051	//�û�����
#define		ID_STR_PRIVILIDEG_DEVICE_MGR		10052	//�豸����
#define		ID_STR_PRIVILIDEG_MEDIA_MGR			10053	//��ý���������ý���������ת�����ã�
#define		ID_STR_PRIVILIDEG_RECORD_MGR		10054	//�洢�������洢���������洢���á�¼��ƻ���
#define		ID_STR_PRIVILIDEG_ALARM_SVR			10055	//��������
#define		ID_STR_PRIVILIDEG_MAP_MGR			10056	//���ӵ�ͼ����
#define		ID_STR_PRIVILIDEG_MATRIX_MGR		10057	//����ǽ����
#define		ID_STR_PRIVILIDEG_DEV_PARA_SETUP	10058	//�豸��������
#define		ID_STR_PRIVILIDEG_ALARM_MGR			10059	//������������
#define		ID_STR_PRIVILIDEG_PREVIEW			10060	//��ƵԤ��
#define		ID_STR_PRIVILIDEG_VOICE_COM			10061	//˫��Խ�
#define		ID_STR_PRIVILIDEG_SNAPSHOT			10062	//ǰ��ץ��
#define		ID_STR_PRIVILIDEG_RECORD_PLAYBACK	10063	//Զ�̻ط�
#define		ID_STR_PRIVILIDEG_PTZ_CTRL			10064	//��̨����
#define		ID_STR_PRIVILIDEG_LOG_QUERY			10065	//��־��ѯ

//////////////////////////////////////////////////////////////////////////
//hw 2013/1/16
#define		ID_STR_PRIVILIDEG_NO_RIGHT			10081	//�û���Ȩ��
//////////////////////////////////////////////////////////////////////////

#define		ID_STR_DLG_LOGIN_ST_USER			10101	//�û�
#define		ID_STR_DLG_LOGIN_ST_PWD				10102	//����
#define		ID_STR_DLG_LOGIN_BTN_LOGIN			10103	//��¼
#define		ID_STR_DLG_LOGIN_ST_SVRIP			10107	//������
#define		ID_STR_DLG_LOGIN_TIP_USER_EMPTY		10108	//�û�����Ϣ�������������룡
#define		ID_STR_DLG_LOGIN_TIP_PWD_EMPTY		10109	//���벻��Ϊ�գ����������룡
#define		ID_STR_DLG_LOGIN_TIP_SVRIP_EMPTY	10110	//��������ַ�������������룡
#define		ID_STR_DLG_LOGIN_TIP_USER_NO_EXIST	10113	//�û������ڣ������������û���Ϣ��
#define		ID_STR_DLG_LOGIN_TIP_PWD_ERROR		10114	//�����������������������Ϣ��
#define		ID_STR_DLG_LOGIN_TITLE				10115	//��¼
#define		ID_STR_DLG_LOGIN_TIP_INPUT			10116	//�������û�������������Ϣ
#define		ID_STR_DLG_LOGIN_TIP_LOGINING		10117	//���ڵ�¼ϵͳ����ȴ�.......
#define		ID_STR_DLG_LOGIN_TIP_USR_ERR		10118	//�û�����������������
#define		ID_STR_DLG_LOGIN_TIP_PWD_ERR		10119	//������������������
#define		ID_STR_DLG_LOGIN_TIP_CNT_ERR		10120	//�޷����ӷ�����������������
#define		ID_STR_DLG_LOGIN_TIP_CNT_SUC		10121	//��¼�ɹ�,���������,���Ժ�...
#define		ID_STR_DLG_LOGIN_TIP_FULL_ERR		10122	//�������û����������ʱ����¼��
#define		ID_STR_DLG_LOGIN_TIP_LOADING_INFO	10123	//���ڷ�������ȡ��Ϣ����ȴ�......
#define		ID_STR_DLG_LOGIN_TIP_LOADING_FD		10124	//��ȡ��Ϣʧ�ܣ������ԣ�
#define		ID_STR_DLG_LOGIN_RELOGIN_TITLE		10125	//���µ�¼
#define		ID_STR_DLG_LOGIN_TIP_VER_ERR		10127	//�汾��Ϣ��ƥ�䣬��ʹ�����°汾�ͻ��ˣ�
#define		ID_STR_DLG_LOGIN_TIP_EXIST			10128	//�û��ѵ�¼
#define		ID_STR_DLG_LOGIN_ST_COMPANY			10129	//��˾
#define		ID_STR_DLG_LOGIN_TIP_CMP_ERR		10130	//��˾��Ϣ�������������룡
#define		ID_STR_DLG_LOGIN_TIP_USER_DEL		10131	//�û���ɾ�������������룡
#define		ID_STR_DLG_LOGIN_TIP_USER_EXPIRED	10132	//�û��ѹ��ڣ����������룡
#define		ID_STR_DLG_LOGIN_TIP_UPGRADE		10133	//����������������ܼ���ʹ�ã��Ƿ�������
#define     ID_STR_DLG_LOGIN_TIP                10134   //�������û�����Ϣ
#define		ID_STR_DLG_LOGIN_UPGRADE_LEASTEST	10135	//���������°汾
#define		ID_STR_DLG_LOGIN_UPGRADE_NEXTTIME	10136	//�´��ٽ�������
#define		ID_STR_DLG_LOGIN_UPGRADE_HIGHEST	10137	//�ͻ��˰汾�ȷ������汾�ߣ�����վ���������ذ�װ����
#define		ID_STR_DLG_LOGIN_UPGRADE_TITLE		10138	//�ͻ���������ʾ
#define     ID_STR_DLG_LOGIN_SAVE_PSW			10139   //��ס����
#define     ID_STR_DLG_LOGIN_AUTO_LOGIN			10140   //�Զ���¼

#define		ID_STR_MODIFY_ERROR				10525	//����ʧ�ܣ�����ԭ��
#define		ID_STR_MODIFY_NET_ERR			10526	//�������
#define		ID_STR_MODIFY_RIGHT_ERR			10527	//�û���Ȩ��
#define		ID_STR_MODIFY_PARAM_ERR			10528	//��������
#define		ID_STR_MODIFY_DB_ERR			10529	//�������ݿ�ʧ��
#define		ID_STR_MODIFY_NAME_USED			10530	//�����ѱ�ռ��
#define		ID_STR_MODIFY_NO_EXIST			10531	//��Ϣ������
#define		ID_STR_MODIFY_ADMIN_ERR			10532	//����Ա�鲻�ñ༭
#define		ID_STR_MODIFY_GROUP_USED		10533	//�û��黹��ռ��
#define		ID_STR_MODIFY_UNKNOWN			10534	//δ֪����
#define		ID_STR_MODIFY_IDNO_USED			10535	//���к��Ѿ���ռ��
#define		ID_STR_MODIFY_SVR_EMPTY			10536	//��������Ϣ������
#define		ID_STR_MODIFY_SVR_DIS_ONLINE	10537	//������������
#define		ID_STR_MODIFY_OBJ_NO_EXIST		10538	//��ͼ��������Ӧ�Ķ�����Ϣ
#define		ID_STR_MODIFY_MAP_USED			10539	//��ͼ��Ϣ����ʹ��
#define		ID_STR_MODIFY_OBJ_DEFINDED		10540	//������Ϣ���ڵ�ͼ�ϱ�ʶ���������ظ���ʶ
#define		ID_STR_MODIFY_USR_NO_EXIST		10541	//�û�������
#define		ID_STR_MODIFY_DEV_NO_EXIST		10542	//�豸��Ϣ������
#define		ID_STR_MODIFY_MAP_NO_EXIST		10543	//��ͼ������
#define		ID_STR_MODIFY_DEV_DIS_ONLINE	10544	//�豸������
#define		ID_STR_MODIFY_DEV_NO_RESP		10545	//û���յ��豸�Ļ�Ӧ
#define		ID_STR_MODIFY_CNT_DS_FAILED		10546	//���ķ���������ʧ��
#define		ID_STR_MODIFY_CNT_MS_FD			10547	//������ý��ת��������ʧ��
#define		ID_STR_MODIFY_MSVR_EMPTY		10548	//δ������ý��ת��������
#define		ID_STR_MODIFY_MS_DOWNING		10550	//��ý��ת��������������Ӧ�����ͻ��˵�������������ԣ�
#define		ID_STR_MODIFY_MS_DISCONNECT		10551	//����ý��ת�����������������ж�
#define		ID_STR_MODIFY_MS_TIMEOUT		10552	//��ȡ���ݳ�ʱ
#define		ID_STR_MODIFY_MS_UPLOADING		10553	//��ý��ת��������������Ӧ�����ͻ��˵��ϴ�������������ԣ�
#define		ID_STR_MODIFY_DEV_DUEING		10554	//�����������ͻ��˽��жԽ�
#define		ID_STR_MODIFY_DEV_TRAN_MSVR_EMPTY	10555	//δ�����ط�������ת����������ַ��Ϣ
#define		ID_STR_MODIFY_DEV_ENT_FAILED	10556	//���ط����������ж�
#define		ID_STR_MODIFY_CNT_MS_SUC		10557	//������ý��������ɹ�
#define		ID_STR_MODIFY_DEV_REC_POS_EMPTY	10558	//û��Ϊ����ָ���洢�������������ݴ洢��
#define		ID_STR_MODIFY_RSVR_DISONLINE	10559	//�洢�����������ߣ��޷����Ӵ洢��������
#define		ID_STR_MODIFY_RSVR_CNT_FIALED	10560	//�洢�����������ж�
#define		ID_STR_MODIFY_FILE_EXT_ERR		10561	//�ļ���ʽ����
#define		ID_STR_MODIFY_FILE_NO_EXIST		10562	//�������ϲ����ڴ��ļ�	
#define		ID_STR_MODIFY_FILE_DOWN_OK		10563	//�ļ���ȫ���������
#define		ID_STR_MODIFY_FILE_DOWN_ING		10564	//�ļ���������
#define		ID_STR_MODIFY_CREATE_TEMP_FILE	10565	//������ʱ�ļ�ʧ�ܣ�
#define		ID_STR_MODIFY_MTX_WND_LARGER	10566	//������Ŵ��󣡵���ǽӵ�еĴ�����Ŀ�ȴ����С��
#define		ID_STR_MODIFY_MTX_DEVICE_USED	10567	//�������豸�Ѿ������������϶��壡
#define		ID_STR_MODIFY_ALARMSVR_SUPPORT_ONE	10568	//ϵͳֻ֧�ֵ���������������
#define		ID_STR_MODIFY_SERVICE_UNVALID	10569	//ϵͳ��Դ���ƣ���������ԣ�
#define		ID_STR_MODIFY_CNT_LS_FD			10570	//���ӽ��������ʧ��
#define		ID_STR_MODIFY_MS_DEV_FULL		10571	//ý�������֧������
#define		ID_STR_MODIFY_SESSION_EXIST		10572	//�豸�Ự��Ϣ�Ѿ�����
#define     ID_STR_MODIFY_SESSION_LIMIT		10573	///�豸�Ự��Ŀ����
#define		ID_STR_MODIFY_SRV_NO_RESP		10574	//����������Ӧ
#define		ID_STR_MODIFY_FILE_USED			10575	//�ļ���ռ��
#define		ID_STR_MODIFY_DISK_ERR			10576	//���������޷���д���ļ�

#define		ID_STR_DLG_PANE_DEVICE			11001	//�ն��б�
#define		ID_STR_DLG_CONTRL_ALL_GROUP			11003	//���з���
#define		ID_STR_DLG_PANE_PLAY			11004	//Զ�̻ط�
#define		ID_STR_DLG_PANE_CAM				11005	//��ͷ����
#define		ID_STR_DLG_PANE_BCAST			11006	//�Խ����㲥
#define		ID_STR_DLG_PANE_DEV_AREA_LIST		11007	//�����б�
#define		ID_STR_TRAINING					11008		//ѵ����
#define		ID_STR_EXAMINATION				11009		//����
#define		ID_STR_AREA_DEV					11010		//�����豸
#define		ID_STR_DEV_LIST					11011		//�����б�
#define		ID_STR_CAR						11012		//����

#define		ID_STR_DLG_VIEW_REQ_ING				16001	//���ڻ�ȡ��Ƶ...
#define		ID_STR_DLG_VIEW_REQ_SUC				16002	//������Ƶ�ɹ�
#define		ID_STR_DLG_VIEW_CNT_DS_FD			16003	//����Ŀ¼������ʧ�ܣ���������������ȴ�...
#define		ID_STR_DLG_VIEW_REQ_USR_NORIGHT		16004	//�û���Ȩ�޲鿴�豸��Ƶ��
#define		ID_STR_DLG_VIEW_REQ_MS_EMPTY		16005	//��ȡ��ý���������Ϣʧ�ܣ���������������ȴ�...
#define		ID_STR_DLG_VIEW_REQ_CNT_MS_FD		16006	//������ý�����ʧ�ܣ���������������ȴ�...
#define		ID_STR_DLG_VIEW_START_VIEW			16007	//��ʼԤ��
#define		ID_STR_DLG_VIEW_STOP_VIEW			16008	//ֹͣԤ��
#define		ID_STR_DLG_VIEW_START_POLLING		16009	//��ʼ��ѯ
#define		ID_STR_DLG_VIEW_STOP_POLLING		16010	//ֹͣ��ѯ
#define		ID_STR_DLG_VIEW_START_AUDIO			16011	//������
#define		ID_STR_DLG_VIEW_STOP_AUDIO			16012	//�ر�����
#define		ID_STR_DLG_VIEW_CAPTURE				16013	//ץ��ͼƬ
#define		ID_STR_DLG_VIEW_FULL_SCREEN			16014	//ȫ����ʾ
#define		ID_STR_DLG_VIEW_START_DUE			16015	//��ʼ�Խ�
#define		ID_STR_DLG_VIEW_STOP_DUE			16016	//ֹͣ�Խ�
#define		ID_STR_DLG_VIEW_SETUP				16017	//Ԥ������
#define		ID_STR_DLG_VIEW_DEV_SETUP			16018	//��������
#define		ID_STR_DLG_VIEW_BAR_WND				16019	//����
#define		ID_STR_DLG_VIEW_START_ALL			16020	//��������Ԥ��
#define		ID_STR_DLG_VIEW_STOP_ALL			16021	//ֹͣ����Ԥ��
#define		ID_STR_DLG_VIEW_POLLING_ALL			16022	//����������ѯ
#define		ID_STR_DLG_VIEW_STOP_POLLING_ALL	16023	//ֹͣ������ѯ
#define		ID_STR_DLG_VIEW_WND_1				16024	//1����
#define		ID_STR_DLG_VIEW_WND_4				16025	//4����
#define		ID_STR_DLG_VIEW_WND_9				16026	//9����
#define		ID_STR_DLG_VIEW_WND_16				16027	//16����
#define		ID_STR_DLG_VIEW_REQ_CNT_MS_SUC		16028	//������ý�����ɹ�����ȴ�...
#define		ID_STR_DLG_VIEW_REQ_CNT_DEV_FD		16029	//���豸������Ƶʧ�ܣ���ȴ�...
#define		ID_STR_DLG_VIEW_REQ_CNT_DEV_SUC		16030	//���豸������Ƶ�ɹ�����ȴ�...
#define		ID_STR_DLG_VIEW_REQ_DISCNT			16031	//��Ƶ�����жϣ���������������ȴ�...
#define		ID_STR_DLG_VIEW_REQ_USR_FULL		16032	//���豸������Ƶ�ɹ�����ȴ�...
#define		ID_STR_DLG_VIEW_REQ_USR_ERROR		16033	//��Ƶ�����û�������
#define		ID_STR_DLG_VIEW_REQ_USR_UNKNOW		16034	//��Ƶ�����û������ڣ���������������ȴ�...
#define		ID_STR_DLG_VIEW_REQ_UNKNOW			16035	//δ֪������������������ȴ�...
#define		ID_STR_DLG_VIEW_INTO_DIV			16036	//������Ƶ�и�
#define		ID_STR_DLG_VIEW_EXIT_DIV			16037	//�˳���Ƶ�и�
#define		ID_STR_DLG_VIEW_CLOSE_DIV			16038	//�ر���Ƶ
#define		ID_STR_DLG_VIEW_IA_SETUP			16039	//���ܷ�������
#define		ID_STR_DLG_VIEW_IA_SHOW				16040	//���ܷ���Ԥ��
#define		ID_STR_DLG_VIEW_STOP_PLAY			16041	//ֹͣ����
#define		ID_STR_DLG_VIEW_PLAY_PAUSE			16042	//����//��ͣ
#define		ID_STR_DLG_VIEW_PLAY_FAST			16043	//���
#define		ID_STR_DLG_VIEW_PLAY_SLOW			16044	//����
#define		ID_STR_DLG_VIEW_PLAY_CAPTURE		16045	//ץ��ͼƬ
#define		ID_STR_DLG_VIEW_PLAY_STEP			16046	//��֡��
#define		ID_STR_DLG_VIEW_DEV_PREVIEWING		16047	//����Ԥ����ͨ����Ƶ��Ϣ��
#define		ID_STR_DLG_VIEW_BUFFER_ING			16048	//��Ƶ������......
#define		ID_STR_DLG_VIEW_PLAY_FAILED			16049	//�ط�ʧ�ܣ�����ԭ��
#define		ID_STR_DLG_VIEW_VIEW_MAIN_STREAM	16050	//Ԥ��������
#define		ID_STR_DLG_VIEW_VIEW_SUB_STREAM		16051	//Ԥ��������
#define		ID_STR_DLG_VIEW_VIEW_DRAG_VIEW		16052	//�϶�Ԥ����������
#define		ID_STR_DLG_VIEW_VIEW_DBCLK_VIEW		16053	//˫��Ԥ����������
#define		ID_STR_DLG_VIEW_MAIN_STREAM			16054	//������
#define		ID_STR_DLG_VIEW_SUB_STREAM			16055	//������
#define		ID_STR_MENU_SHOW_ALARM				16056	//�鿴���±���
#define		ID_STR_MENU_CONFIRM_ALARM			16057	//ȷ�ϱ�����Ϣ
#define		ID_STR_MENU_QUERY_ALARM				16058	//��ѯ������Ϣ
#define		ID_STR_DLG_VIEW_WND_UP				16059	//�����ƶ�����
#define		ID_STR_DLG_VIEW_WND_DOWN			16060	//�����ƶ�����
#define		ID_STR_DLG_VIEW_ADD_BCAST			16061	//����㲥����
#define		ID_STR_DLG_VIEW_START_BCAST			16062	//��ʼ�㲥
#define		ID_STR_DLG_VIEW_DEL_BCAST			16063	//�˳��㲥����
#define		ID_STR_MENU_START_VEHI_RUN			16064	//����ʵʱ���
#define		ID_STR_MENU_STOP_VEHI_RUN			16065	//ֹͣʵʱ���
#define		ID_STR_MENU_START_MONITOR			16066	//��ʼ����
#define		ID_STR_MENU_STOP_MONITOR			16067	//ֹͣ����	
#define		ID_STR_MENU_START_VIDEORECORD		16068	//��ʼ¼��
#define		ID_STR_MENU_STOP_VIDEORECORD		16069	//ֹͣ¼��	
#define		ID_STR_MENU_DISCONNECT_OIL			16070	//�Ͽ���·
#define		ID_STR_MENU_CONNECT_OIL				16071	//����·
#define		ID_STR_MENU_TURNOFF_POWER			16072	//�رյ�Դ
#define		ID_STR_MENU_TURNON_POWER			16073	//�򿪵�Դ	
#define		ID_STR_MENU_RESTART_DEV				16074	//�����豸
#define		ID_STR_MENU_FACTORY_SETTING			16075	//�ָ���������	
#define		ID_STR_MENU_SEND_TEXT				16076	//TTS����
#define		ID_STR_MENU_BROWSE_REC_FILE			16077	//���¼���ļ�
#define		ID_STR_MENU_DEV_INFO				16078	//������Ϣ
#define		ID_STR_MENU_EQUIPMENT_PROMOTE		16079	//�豸����
#define     ID_STR_MENU_DEV_PARAMER_CONF        16080   //�豸��������
#define     ID_STR_DLG_VIEW_VIDIO               16081   //��Ƶ
#define		ID_STR_DLG_VIEW_WND_6				16082	//6����
#define		ID_STR_DLG_VIEW_WND_8				16083	//8����

#define		ID_STR_MENU_DISCONNECT_OIL_SUC		16084	//�Ͽ���·���óɹ�
#define		ID_STR_MENU_CONNECT_OIL_SUC			16085	//����·���óɹ�
#define		ID_STR_MENU_TURNOFF_POWER_SUC		16086	//�رյ�Դ���óɹ�
#define		ID_STR_MENU_TURNON_POWER_SUC		16087	//�򿪵�Դ���óɹ�	
#define		ID_STR_MENU_RESTART_DEV_SUC			16088	//�����豸���óɹ�
#define		ID_STR_MENU_FACTORY_SETTING_SUC		16089	//�ָ��������óɹ�
#define		ID_STR_MENU_DISCONNECT_OIL_F		16090	//�Ͽ���·����ʧ��
#define		ID_STR_MENU_CONNECT_OIL_F			16091	//����·����ʧ��
#define		ID_STR_MENU_TURNOFF_POWER_F			16092	//�رյ�Դ����ʧ��
#define		ID_STR_MENU_TURNON_POWER_F			16093	//�򿪵�Դ����ʧ��	
#define		ID_STR_MENU_RESTART_DEV_F			16094	//�����豸����ʧ��
#define		ID_STR_MENU_FACTORY_SETTING_F		16095	//�ָ���������ʧ��
#define		ID_STR_MENU_START_ALL_RECORD		16096	//��������¼��
#define		ID_STR_MENU_STOP_ALL_RECORD			16097	//�ر�����¼��
#define		ID_STR_MENU_START_PICTURE			16098	//����ͼƬԤ��
#define		ID_STR_MENU_STOP_PICTURE			16099	//����ͼƬԤ��

#define		ID_STR_DLG_VIEW_MGR_ST_WND			16101	//Ԥ������
#define		ID_STR_DLG_VIEW_MGR_WINDOW			16102	//����
#define		ID_STR_DLG_VIEW_MGR_ST_POLLING		16103	//��ѯ�б�
#define		ID_STR_DLG_VIEW_MGR_ST_TYPE			16104	//Ԥ������
#define		ID_STR_DLG_VIEW_MGR_ST_TIME			16105	//��ѯʱ��
#define		ID_STR_DLG_VIEW_MGR_ST_TM_RANGE		16106	//(15~300��)
#define		ID_STR_DLG_VIEW_MGR_TYPE_MAIN		16107	//������
#define		ID_STR_DLG_VIEW_MGR_TYPE_SUB		16108	//������
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_DEV	16109	//�豸
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_CHAN	16110	//ͨ��
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_TYPE	16111	//����
#define		ID_STR_DLG_VIEW_MGR_LIST_POLL_TIME	16112	//ʱ��
#define		ID_STR_DLG_VIEW_MGR_TIP_TIME_ERR	16113	//��ѯʱ����Χ����
#define		ID_STR_DLG_VIEW_MGR_TIP_NODE_EXIST	16114	//�Ѿ�����ͬһ�豸ͬһͨ������Ϣ
#define		ID_STR_DLG_VIEW_MGR_TIP_POLLING_ERR	16115	//����������ѯ����ֹͣ��ѯ���ٽ��в������Ƿ�ֹͣ��ѯ��
#define		ID_STR_DLG_VIEW_MGR_BTN_UP			16116	//��
#define		ID_STR_DLG_VIEW_MGR_BTN_DOWN		16117	//��
#define		ID_STR_DLG_VIEW_MGR_TITLE			16118	//��Ƶ��ѯ����
#define     ID_STR_DLG_VIEW_MGR_POLLING_NEW     16119   //������ѯ - 
#define     ID_STR_DLG_VIEW_SHOW_TITLE		    16120   //��ʾ����
#define     ID_STR_DLG_VIEW_HIDE_TITLE		    16121   //���ر��� 

#define		ID_STR_DLG_SHOW_SYSTEM_WND			19986	//��ʾϵͳ����
#define		ID_STR_DLG_HIDE_SYSTEM_WND			19987	//����ϵͳ����
#define		ID_STR_DLG_EVENT_HIDE_RIGHT_WND		19988	//�����Ҳര��
#define		ID_STR_DLG_EVENT_SHOW_RIGHT_WND		19989	//��ʾ�Ҳര��
#define		ID_STR_DLG_EVENT_HIDE_EVEN_PANE		19990	//��С���¼����
#define		ID_STR_DLG_EVENT_SHOW_EVEN_PANE		19991	//��ʾ�¼����

#define		ID_STR_DLG_EVENT_RUNINT_ACC_OFF_0	19992	//ͣ��δϨ��
#define		ID_STR_DLG_EVENT_RUNINT_ALARM_0		19993	//����
#define		ID_STR_DLG_EVENT_RUNINT_OFFLINE_0	19994	//����
#define		ID_STR_DLG_EVENT_RUNINT_DEV_0		19995	//��������

#define		ID_STR_DLG_EVENT_RUNINT_ACC_OFF		19996	//ͣ��δϨ��ĳ���
#define		ID_STR_DLG_EVENT_RUNINT_ALARM		19997	//�����ĳ���
#define		ID_STR_DLG_EVENT_RUNINT_OFFLINE		19998	//���ߵĳ���
#define		ID_STR_DLG_EVENT_RUNINT_DEV			19999	//�������еĳ���
#define		ID_STR_DLG_EVENT_LST_OTHER_INFO		20000	//������Ϣ
#define		ID_STR_DLG_EVENT_LST_ALARM_TIME		20001	//ʱ��
#define		ID_STR_DLG_EVENT_LST_ALARM_TYPE		20002	//����
#define		ID_STR_DLG_EVENT_LST_ALARM_INFO		20004	//����
#define		ID_STR_DLG_EVENT_MENU_CLEAR			20005	//����¼�
#define		ID_STR_DLG_EVENT_LST_REAL_VEHI		20006	//����
#define		ID_STR_DLG_EVENT_LST_REAL_SPEED		20007	//�ٶ�
#define		ID_STR_DLG_EVENT_LST_REAL_LONG		20008	//����
#define		ID_STR_DLG_EVENT_LST_REAL_LAT		20009	//γ��
#define		ID_STR_DLG_EVENT_LST_REAL_TIME		20010	//GPSʱ��
#define		ID_STR_DLG_EVENT_LST_REAL_RV_TIME	20011	//����ʱ��
#define		ID_STR_DLG_EVENT_LST_REAL_ONLINE	20012	//����
#define		ID_STR_DLG_EVENT_LST_REAL_STATUS	20013	//״̬
#define		ID_STR_DLG_EVENT_LST_REAL_CONFIRM	20014	//����״̬
#define		ID_STR_DLG_EVENT_LST_INFO_TIME		20015	//ʱ��
#define		ID_STR_DLG_EVENT_LST_INFO_TYPE		20016	//����
#define		ID_STR_DLG_EVENT_LST_INFO_INFO		20017	//����
#define		ID_STR_DLG_EVENT_LST_REAL_MAP		20018	//��ͼ��ʾ
#define		ID_STR_MENU_VEHI_RUN_STOP			20019	//ֹͣʵʱ���
#define		ID_STR_MENU_VEHI_RUN_CLEAR			20020	//���ʵʱ���
#define		ID_STR_MENU_VEHI_MAP				20021	//ʵʱ���ٳ���
#define		ID_STR_MENU_VEHI_MAP_DEL			20022	//ȡ�����ٳ���
#define		ID_STR_MENU_VEHI_MAP_CENTER			20023	//�Գ���Ϊ����
#define		ID_STR_MENU_VEHI_DEL_CENTER			20024	//ȡ������Ϊ����
#define		ID_STR_CHANGE_TO_MAP_VIEW			20025	//��ǰ������ƵԤ�����棡�Ƿ��л������ӵ�ͼ�������λ����ʾ��
#define		ID_STR_MENU_ALARM_UNVERIFY			20026	//�鿴δȷ�ϱ���
#define		ID_STR_MENU_ALARM_MAP				20027	//��ͼ��ʾ����
#define		ID_STR_MENU_ALARM_QUERY				20028	//��ѯ���౨��
#define		ID_STR_MENU_ALARM_CLEAR				20029	//��ձ���
#define		ID_STR_EVENT_LIST_ALRM_NOCONFRIM	20030	//δ��������
#define		ID_STR_EVENT_LIST_ALRM_CONFRIMED	20031	//�Ѵ�������
#define		ID_STR_EVENT_LIST_ALRM_NONEED		20032	//���账��
#define		ID_STR_MENU_ALARM_MAP_CLEAR			20033	//��ͼ�������
#define		ID_STR_DEV							20034	//�ն�
#define		ID_STR_DLG_EVENT_AUTO_SORT			20035	//�Զ�����

#define		ID_STR_DLG_EVENT_TAB_REAL			20041	//GPS���
#define		ID_STR_DLG_EVENT_TAB_ALARM			20042	//������Ϣ
#define		ID_STR_DLG_EVENT_TAB_INFO			20043	//ϵͳ�¼�

#define		ID_STR_MOBILE_DEV_SEX				20050	//�Ա�
#define		ID_STR_MOBILE_DEV_ID_CAR			20051	//����֤
#define		ID_STR_MOBILE_DEV_USER_NUM			20052	//���
#define		ID_STR_MOBILE_DEV_POST				20053	//ְ��

#define		ID_STR_MOBILE_DEV_EQUIP				20055	//װ��
#define		ID_STR_MOBILE_DEV_ADDRESS			20056	//סַ
#define		ID_STR_MOBILE_DEV_GROUP				20057	//��������

#define		ID_STR_MOBILE_DEV_TEAM_LEADER		20060	//�ӳ�
#define		ID_STR_MOBILE_DEV_TEAM_MEMBER		20061	//��Ա
#define		ID_STR_MOBILE_DEV_SEX_MAN			20062	//��
#define		ID_STR_MOBILE_DEV_SEX_WOMAN			20063	//Ů


#define		ID_STR_VEHI_RUN_FULL				20071	//��ͼ�������ʾ%d�����Ƿ�����滻��ʾ��
#define		ID_STR_TEMPERATOR_DEVICE			20072	//�豸�¶�
#define		ID_STR_TEMPERATOR_MOTER				20073	//�������¶�
#define		ID_STR_TEMPERATOR_COACH				20074	//�����¶�
#define		ID_STR_VEHI_REAL_FULL				20075	//ϵͳ�Ѿ�ͬʱ����%d�����������������ӳ������٣�
#define		ID_STR_VEHI_DIRECTION				20076	//����
#define		ID_STR_NORTH						20077	//��
#define		ID_STR_NORTH_EAST					20078	//����
#define		ID_STR_EAST							20079	//��
#define		ID_STR_SOUTH_EAST					20080	//����
#define		ID_STR_SOUTH						20081	//��
#define		ID_STR_SOUTH_WEST					20082	//����
#define		ID_STR_WEST							20083	//��
#define		ID_STR_NORTH_WEST					20084	//����
#define		ID_STR_DIRECTION_INVALID			20085	//��Ч	

#define		ID_STR_DLG_TABCK_BROAD_ERR			21001	//���ڽ��й㲥���޷��ٽ��жԽ�������
#define		ID_STR_DLG_TABCK_OPEN_ERR			21002	//�����Խ�ʧ�ܣ�ϵͳ����������豸����������ѱ���������ռ�ã�
#define		ID_STR_DLG_TABCK_DEV_DUEING			21003	//�豸�Ѿ��ڶԽ����������ظ����ӣ�
#define		ID_STR_DLG_TABCK_LST_DEV			21004	//�Խ�����
#define		ID_STR_DLG_TABCK_LST_STATUS			21005	//�Խ�״̬
#define		ID_STR_DLG_TABCK_LST_GROUP			21006	//��������
#define		ID_STR_DLG_TABCK_DEV_REQING			21007	//��������Խ�.....
#define		ID_STR_DLG_TABCK_ING				21008	//�Խ���......
#define		ID_STR_DLG_TABCK_MENU_STOP			21009	//ֹͣ�Խ�
#define		ID_STR_DLG_TABCK_MENU_STOP_ALL		21010	//ֹͣȫ��
#define		ID_STR_DLG_TABCK_GROUP_NAME			21011	//����

#define		ID_STR_DLG_DOWNLOAD_TITLE			24001	//���ڴ��豸��ȡ����
#define		ID_STR_DLG_DOWNLOAD_SNAPSHOT		24002	//���ڴ��豸��ȡץ�����ݣ���ȴ�......
#define		ID_STR_DLG_DOWNLOAD_GETALLCFG		24003	//���ڴ��豸��ȡ���в�������ȴ�......
#define		ID_STR_DLG_DOWNLOAD_DOWN_FAILED		24004	//��ȡ����ʧ�ܣ�
#define		ID_STR_DLG_DOWNLOAD_DOWNING			24005	//������������������ݣ���ȴ�......

#define		ID_STR_DLG_UPLOAD_TITLE				25001	//���ڴ��豸��ȡ����
#define		ID_STR_DLG_UPLOAD_SETALLCFG			25002	//���ڴ��豸�ϴ��������ݣ���ȴ�......
#define		ID_STR_DLG_UPLOAD_UPLOADING			25003	//�����豸�ϴ����ݣ���ȴ�......
#define		ID_STR_DLG_UPLOAD_FAILED			25004	//�ϴ�����ʧ�ܣ�

#define		ID_STR_DLG_VOIP_TITLE				25021	//��������
#define		ID_STR_DLG_VOIP_BCAST				25022	//�㲥
#define		ID_STR_DLG_VOIP_TBACK				25023	//�Խ�
#define		ID_STR_DLG_VOIP_MONITOR				25024	//����
#define		ID_STR_DLG_VOIP_TIP_STOP_TBACK		25025	//��ǰ���ڶԽ���,ȷ���ر�?
#define		ID_STR_DLG_VOIP_TIP_STOP_BCAST		25026	//��ǰ���ڹ㲥��,ȷ���ر�?
#define		ID_STR_DLG_VOIP_CONFILCK_TABCK		25027	//�Խ���㲥,��Ƶ�������߼�����ͻ,�Ƿ�رյ�ǰ�ĶԽ�?
#define		ID_STR_DLG_VOIP_CONFLICK_BCAST		25028	//�㲥��Խ���ͻ,�Ƿ�رյ�ǰ�Ĺ㲥?
#define		ID_STR_DLG_VOIP_DEV_STOP_CNT		25029	//�豸ֹͣͨ��
#define		ID_STR_DLG_VOIP_DEV_START			25030	//����
#define		ID_STR_DLG_VOIP_DEV_STOP			25031	//ֹͣ
#define		ID_STR_DLG_VOIP_DEV_SELECT			25032	//ѡ��

#define		ID_STR_DLG_MONITOR_SUCCESS			25041	//���������ɹ�
#define		ID_STR_DLG_MONITOR_FAILED			25042	//��������ʧ��
#define		ID_STR_DLG_MONITOR_MENU_STOP		25043	//ֹͣ����
#define		ID_STR_DLG_MONITOR_LST_DEV			25044   //��������
#define		ID_STR_DLG_MONITOR_LST_POS			25045	//����λ��
#define		ID_STR_DLG_MONITOR_LST_STATUS		25046   //����״̬
#define		ID_STR_DLG_MONITOR_LST_GROUP		25047	//��������
#define		ID_STR_DLG_MONITOR_DEV_ISEXIT		25048	//�豸�Ѿ��ڼ������������ظ����ӣ�
#define		ID_STR_DLG_MONITOR_OPEN_ERR			25049	//����������ʧ��!
#define     ID_STR_DLG_MONITOR_REQUSTING		25050	//������......
#define		ID_STR_DLG_MONITRO_MIC_CHANNEL		25051	//���

#define		ID_STR_DLG_BCAST_DUE_ERR			26001	//���ڽ��жԽ����޷��ٽ��������㲥������
#define		ID_STR_DLG_BCAST_OPEN_ERR			26002	//���������㲥ʧ�ܣ�ϵͳ����������豸����������ѱ���������ռ�ã�
#define		ID_STR_DLG_BCAST_DEV_DUEING			26003	//�Ѿ��Լ�ط��������������㲥��
#define		ID_STR_DLG_BCAST_GROUP_DUEING		26004	//�Ѿ��Դ���ļ�ط��������������㲥��
#define		ID_STR_DLG_BCAST_ING				26005	//�㲥��......
#define		ID_STR_DLG_BCAST_BTN_SOUND			26006	//��Ϣ
#define		ID_STR_DLG_BCAST_BTN_DEL			26007	//ɾ��
#define		ID_STR_DLG_BCAST_BTN_STOP			26008	//ֹͣ
#define		ID_STR_DLG_BCAST_MENU_DEL			26009	//ɾ���㲥
#define		ID_STR_DLG_BCAST_MENU_STOP			26010	//ֹͣ�㲥
#define		ID_STR_DLG_BCAST_MENU_EVENT			26011	//��ʾ�¼�
#define		ID_STR_DLG_BCAST_MENU_CLEAR_EVENT	26012	//����¼�
#define		ID_STR_DLG_BCAST_LIST_DEVICE		26013	//�㲥����
#define		ID_STR_DLG_BCAST_LIST_STATUS		26014	//״̬
#define		ID_STR_DLG_BCAST_LIST_GROUP			26015	//��������
#define		ID_STR_DLG_BCAST_LIST_SOUND			26016	//��������
#define     ID_STR_DLG_BCAST_LIST_NO            26017   //��      
#define     ID_STR_DLG_BCAST_ALARM_STATUS       26018   //����״̬ 
#define     ID_STR_DLG_BCAST_DRIVER_NAME        26019   //˾��
#define     ID_STR_DLG_BCAST_GPS_TIME           26020   //gpsʱ��

#define		ID_STR_DLG_REC_SEARCH_RECTYPE_NORMAL	27001	//����¼��
#define		ID_STR_DLG_REC_SEARCH_RECTYPE_ALARM		27002	//����¼��
#define		ID_STR_DLG_REC_SEARCH_LOCATION_DEV		27003	//��ط�����
#define		ID_STR_DLG_REC_SEARCH_LOCATION_RSVR		27004	//�洢������
#define		ID_STR_DLG_REC_SEARCH_RECTYPE_ALL		27005	//����¼��
#define		ID_STR_DLG_REC_SEARCH_LIST_SEARCH		27006	//�����б�
#define		ID_STR_DLG_REC_SEARCH_LIST_DOWNING		27007	//��������
#define		ID_STR_DLG_REC_SEARCH_ST_DEVICE			27008	//��ط�����
#define		ID_STR_DLG_REC_SEARCH_BTN_SEARCH		27009	//����
#define		ID_STR_DLG_REC_SEARCH_BTN_DOWNLOAD		27010	//��������
#define		ID_STR_DLG_REC_SEARCH_BTN_PLAYBACK		27011	//�ط�
#define		ID_STR_DLG_REC_SEARCH_BTN_DOWN_CONFIG	27012	//��������
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_TIME	27013	//ʱ��
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_TYPE	27014	//����
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_FILE	27015	//�ļ�
#define		ID_STR_DLG_REC_SEARCH_LST_SEARCH_CHN	27016	//ͨ��
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_FILE		27017	//�ļ�
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_PROCESS	27018	//���ؽ���
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_LOCATION	27019	//�洢λ��
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_REC_LOACATION	27020	//λ��
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_DEV		27021	//��ط�����
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_SIZE		27022	//��С
#define		ID_STR_DLG_REC_SEARCH_ED_DEVICE_TIP		27023	//�뽫��ط������϶�����λ��
#define		ID_STR_DLG_REC_SEARCH_TIP_SEARCHING		27024	//�����������Ƿ�ֹͣ�������������Դ˼�ط���������������
#define		ID_STR_DLG_REC_SEARCH_STOP_SEARCHING	27025	//�����������Ƿ�ֹͣ������
#define		ID_STR_DLG_REC_SEARCH_BTN_STOP_SEARCH	27026	//ֹͣ
#define		ID_STR_DLG_REC_SEARCH_TIP_DEV_EMPTY		27027	//�����ý��������ļ�ط����������÷������Ӽ�ط������б���\r\n���б��϶���������ϵļ�ط����������ϡ�
#define		ID_STR_DLG_REC_SEARCH_LIST_DOWN_OK		27028	//������
#define		ID_STR_DLG_REC_SEARCH_TIME_ERROR		27029	//��ʼʱ�����С�ڽ���ʱ��
#define		ID_STR_DLG_REC_SEARCH_ST_TIME			27030	//����ʱ��
#define		ID_STR_DLG_REC_SEARCH_ST_TIME_TO		27031	//��
#define		ID_STR_DLG_REC_SEARCH_ST_REC_TYPE		27032	//¼������
#define		ID_STR_DLG_REC_SEARCH_FAILED			27033	//����ʧ�ܣ�����ԭ��
#define		ID_STR_DLG_REC_SEARCH_DOWNING_ERR		27034	//��������¼���ļ�����֧��ͬʱ���ض��¼���ļ���
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_STATUS	27035	//״̬
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_ING		27036	//��������
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_FAILED	27037	//����ʧ��
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_SUC		27038	//���سɹ�
#define		ID_STR_MENU_DFILE_STOP					27039	//ֹͣ����
#define		ID_STR_MENU_DFILE_DELETE				27040	//ɾ������
#define		ID_STR_MENU_DFILE_OPEN					27041	//���ļ���
#define		ID_STR_MENU_DFILE_PLAY					27042	//�����ļ�
#define		ID_STR_MENU_DFILE_REDOWN				27043	//��������
#define		ID_STR_DLG_REC_SEARCH_START_DOWN_FAILED	27044	//�����ļ�ʧ��
#define		ID_STR_DLG_REC_SEARCH_DOWN_FAILED		27045	//�����ļ�ʧ�ܣ�����ԭ��
#define		ID_STR_DLG_REC_SEARCH_DOWN_DELETE		27046	//�Ƿ�ͬʱɾ�����ص�¼���ļ���
#define		ID_STR_DLG_REC_SEARCH_DOWN_DELETE_ING	27047	//�ļ��������أ���ɾ������ִ�����ز���
#define		ID_STR_DLG_REC_SEARCH_DOWN_REDOWN		27048	//�ļ��Ѿ����سɹ����������ؽ�ɾ���ļ����Ƿ��������أ�
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_STOP		27049	//ֹͣ����
#define		ID_STR_DLG_REC_SEARCH_DOWN_ED			27050	//�ļ��Ѿ����سɹ���
#define		ID_STR_MENU_RECSEARCH_PLAY				27051	//¼��ط�
#define		ID_STR_MENU_RECSEARCH_DOWN				27052	//��������
#define		ID_STR_DLG_REC_SEARCH_PLAY_NO_DOWN_OK	27053	//�ļ�û�����سɹ��������سɹ���ִ�в��Ų���
#define		ID_STR_DLG_REC_SEARCH_WND_USED			27054	//��ǰ����δ���ڿ���״̬����ѡ����������ѡ�񲥷Ų�����
#define		ID_STR_DLG_RECS_PLAY_TYPE_LOCAL			27055	//���ػط�
#define		ID_STR_DLG_RECS_PLAY_TYPE_REMOTE		27056	//Զ�̻ط�
#define		ID_STR_DLG_RECS_PLAY_NONE				27057	//δ����¼��ط�
#define		ID_STR_DLG_RECS_PLAY_RUNNING			27058	//���ļ��Ѿ����ڲ���״̬��
#define		ID_STR_DLG_RECS_DEL_PLAY_RUNNING		27059	//�ļ����ڲ��ţ��޷�ִ��ɾ��������
#define		ID_STR_MENU_DFILE_PATH					27060	//����·������
#define		ID_STR_DLG_RECS_ST_PLAY					27061	//���ſ���
#define		ID_STR_DLG_RECS_ST_DOWN					27062	//����������
#define		ID_STR_DLG_RECS_ERRCH_LOACTION_DISK		27063	//���ش���
#define     ID_STR_DLG_RECS_ST_FILE_TYPE			27064	//�ļ�����
#define		ID_STR_DLG_RECS_CMB_FILE_TYPE_JPEG		27065	//ͼƬ
#define		ID_STR_DLG_RECS_CMB_FILE_TYPE_RECORD	27066	//¼��
#define		ID_STR_DLG_RECS_ST_JPEG_TYPE			27067	//ͼƬ����
#define		ID_STR_DLG_RECS_BTN_PIC_PREVIEW			27068	//Ԥ��ͼƬ
#define		ID_STR_DLG_RECS_LIST_DOWN_TIP			27069	//������ʾ
#define		ID_STR_DLG_RECS_LIST_DOWN_EXIST			27070	//�Ѿ����������б���
#define		ID_STR_DLG_RECS_LIST_DOWN_WAITING		27071	//�ȴ���
#define		ID_STR_DLG_RECS_BTN_DOWN_TASK			27072	//Զ������
#define		ID_STR_DLG_RECS_TASK_SUBMIT_SUCCESS		27073	//�����ύ�ɹ�!
#define		ID_STR_DLG_RECS_TASK_SUBMIT_FAILED		27074	//�����ύʧ��!
//#define		ID_STR_MENU_RECSEARCH_TASK				27076	//Զ������
#define     ID_STR_DLG_RECS_ERRCH_DOWNLOAD_SER      27075   //���ط�����
#define		ID_STR_DLG_REC_SEARCH_LST_DOWN_RATE		27076	//�����ٶ�
#define		ID_STR_DLG_REC_SEARCH_LST_TIP			27077	//˫��¼���б��򿪻طŷ���������
#define		ID_STR_DLG_REC_SEARCH_LOCATION_DOWN_SERVER			27078	//���ط�����
#define		ID_STR_DLG_REC_GPLAYER_UN_INSTll		27079	//��ϵͳδ��װ�طŷ�������, ���ȷ����������.
#define		ID_STR_DLG_MAPINFO_UN_INSTll			27080	//��ϵͳδ��װmapinfo, ���ȷ����������.
#define		ID_STR_DLG_MAP_CHANGE_REBOOT			27081	//��ͼ�ı䣬ϵͳ��Ҫ����.
#define		ID_STR_DLG_REC_ALL_CHANNEL				27082	//����ͨ��
#define		ID_STR_DLG_REC_SEARCH_RECORD_TIME		27083	//ʱ��
#define		ID_STR_DLG_REC_SEARCH_RECORD_FILE		27084	//�ļ�
#define		ID_STR_DLG_REC_SEARCH_RECORD_DOWN		27085	//����
	

#define		ID_STR_DLG_PLAY_BTN_PLAY				27101	//����
#define		ID_STR_DLG_PLAY_BTN_PAUSE				27102	//��ͣ
#define		ID_STR_DLG_PLAY_BTN_STOP				27103	//ֹͣ
#define		ID_STR_DLG_PLAY_BTN_SLOW				27104	//����
#define		ID_STR_DLG_PLAY_BTN_FAST				27105	//���
#define		ID_STR_DLG_PLAY_BTN_STEP				27106	//I֡����
#define		ID_STR_DLG_PLAY_TIP_PREVIEW				27107	//���л���Ԥ�����ڣ��ٽ��в�����
#define		ID_STR_SEARCH_PLAY						27108	//�������ط�
#define		ID_STR_POSITION							27109	//λ��
#define		ID_STR_DLG_PLAY_BTN_STOP_STEP			27110	//ֹͣI֡
#define		ID_STR_PLAYBACK_TIP						27111	//��ܰ��ʾ:Զ�̻ط�¼���ļ��ϴ�,�طŻ����ͣ��.

#define		ID_STR_DLG_ARMSETUP_TITLE			30001	//������������
#define		ID_STR_DLG_ARMSETUP_ST_TYPE			30002	//��������
#define		ID_STR_DLG_ARMSETUP_ST_ACTION		30003	//��������
#define		ID_STR_DLG_ARMSETUP_ST_TIME			30004	//��������
#define		ID_STR_DLG_ARMSETUP_CHK_TIME		30005	//����
#define		ID_STR_DLG_ARMSETUP_ST_TO			30006	//��
#define		ID_STR_DLG_ARMSETUP_CHK_CENTERMAP	30007	//���е�ͼ
#define		ID_STR_DLG_ARMSETUP_CHK_SHOWTIP		30008	//��Ϣ��ʾ
#define		ID_STR_DLG_ARMSETUP_ST_A_COUNT		30009	//���Ŵ���
#define		ID_STR_DLG_ARMSETUP_ST_A_WAV		30010	//�����ļ�
#define		ID_STR_DLG_ARMSETUP_ST_V_CHN		30011	//Ԥ��ͨ��
#define		ID_STR_DLG_ARMSETUP_CHK_VIDEO		30012	//��ƵԤ��
#define		ID_STR_DLG_ARMSETUP_CHK_AUDIO		30013	//��������
#define		ID_STR_DLG_ARMSETUP_RADIO_IO1		30014	//IO1���뱨��
#define		ID_STR_DLG_ARMSETUP_RADIO_IO2		30015	//I02���뱨��
#define		ID_STR_DLG_ARMSETUP_RADIO_IA		30016	//���ܷ�������
#define		ID_STR_DLG_ARMSETUP_RADIO_DEGREE	30017	//�¶ȱ���
#define		ID_STR_DLG_ARMSETUP_RADIO_NET		30018	//���߱���
#define		ID_STR_DLG_ARMSETUP_RADIO_OTHER		30019	//��������
#define		ID_STR_DLG_ARMSETUP_CHANGE_SAVE		30020	//��������������Ϣ�Ѿ������ı䣬�Ƿ񱣴棿
#define		ID_STR_DLG_ARMSETUP_A_COUNT_ERR		30021	//�������Ŵ�����Χ��1-10֮�䣬���������룡
#define		ID_STR_DLG_ARMSETUP_BTN_SAVE		30022	//����
#define		ID_STR_DLG_ARMSETUP_BTN_APPLy		30023	//���浽�������
#define		ID_STR_DLG_ARMSETUP_BTN_PLAY		30024	//����
#define		ID_STR_DLG_ARMSETUP_ST_A_RANGE		30025	//(1-10)
#define		ID_STR_DLG_ARMSETUP_TIME_ERR		30026	//�����Ŀ�ʼʱ�����С�ڽ���ʱ�䣡���������룡
#define		ID_STR_DLG_ARMSETUP_ST_V_STREAM		30027	//��������
#define     ID_STR_DLG_ARMSETUP_BTN_SETDEF		30028	//����ΪĬ������	
#define     ID_STR_DLG_ARMSETUP_BTN_LOADDEF		30029   //����Ĭ������
#define     ID_STR_DLG_ARMSETUP_ST_PS			30030	//��ע:���ó���û��������������ʱ������Ĭ�����ã�
#define     ID_STR_DLG_ARMSETUP_CH_ALERM_VIDEO  30031   //��������¼��
#define     ID_STR_DLG_ARMSETUP_ALARM_V_COUNT   30032   //¼��ʱ��
#define     ID_STR_DLG_ARMSETUP_ALARM_V_COUNT_W 30033   //��������¼��ʱ�����%d-%d��֮��!
#define     ID_STR_DLG_ARMSETUP_WAV_TIP         30034   //������������,��"���"��.wav��ʽ�ļ�������
#define		ID_STR_DLG_ARMSETUP_TYPE_SPEED		30035	//�ٶȱ���
#define		ID_STR_DLG_ARMSETUP_TYPE_DISK		30036	//Ӳ�̱���
#define		ID_STR_DLG_ARMSETUP_TYPE_VIDEO		30037	//��Ƶ����
#define		ID_STR_DLG_ARMSETUP_TYPE_OTHER		30038	//��������
#define		ID_STR_DLG_ARMSETUP_TYPE_OPERATOR	30039	//��������
#define		ID_STR_DLG_ARMSETUP_TYPE_EXCEPTION	30040	//���ϱ���
#define		ID_STR_DLG_ARMSETUP_DISK2_NO_EXIST	30041	//Ӳ��2������
#define		ID_STR_DLG_ARMSETUP_DISK1_NO_EXIST	30042	//Ӳ��1������
#define		ID_STR_DLG_ARMSETUP_SPEED_LOW		30043	//���ٱ���
#define		ID_STR_DLG_ARMSETUP_SPEED_HIGH		30044	//���ٱ���
#define		ID_STR_DLG_ARMSETUP_TYPE_OIL		30045	//��������
#define		ID_STR_DLG_ARMSETUP_ADD_OIL			30046	//���ͱ���
#define		ID_STR_DLG_ARMSETUP_DEC_OIL			30047	//�������ٱ���

#define		ID_STR_TYPE_UNKNOW					31001	//δ֪
#define		ID_STR_ALARM_TYPE_USEDEFINE			31003	//�Զ��屨��
#define		ID_STR_ALARM_TYPE_URGENCY_BUTTON	31004	//������ť����
#define		ID_STR_ALARM_TYPE_SHAKE				31005	//�񶯱���
#define		ID_STR_ALARM_TYPE_VIDEO_LOST		31006	//��Ƶ���ź�
#define		ID_STR_ALARM_TYPE_VIDEO_MASK		31007	//��Ƶ�ڵ�
#define		ID_STR_ALARM_TYPE_DOOR_OPEN_LAWLESS	31008	//�Ƿ����ű���
#define		ID_STR_ALARM_TYPE_WRONG_PWD			31009	//����������󱨾�
#define		ID_STR_ALARM_TYPE_FIRE_LOWLESS		31010	//�Ƿ���𱨾�
#define		ID_STR_ALARM_TYPE_TEMPERATOR		31011	//�¶ȱ���
#define		ID_STR_ALARM_TYPE_DISK_ERROR		31012	//Ӳ�̴��󱨾�
#define		ID_STR_ALARM_TYPE_OVERSPEED			31013	//����/���ٱ���
#define		ID_STR_ALARM_TYPE_BEYOND_BOUNDS		31014	//Խ�籨��
#define		ID_STR_ALARM_TYPE_DOOR_ABNORMAL		31015	//�쳣���س���
#define		ID_STR_ALARM_TYPE_DEV_ONLINE		31016	//�豸ͨ�Żָ�
#define		ID_STR_ALARM_TYPE_DEV_DISONLINE		31017	//�豸ͨ���ж�
#define		ID_STR_ALARM_CONFIRM				31018	//ȡ������״̬
#define		ID_STR_ALARM_START					31019	//������ʼ
#define		ID_STR_ALARM_END					31020	//��������
#define     ID_STR_ALARM_TYPE_ACC_ON            31021   //ACC��������
#define     ID_STR_ALARM_TYPE_ACC_OFF           31022   //ACC�رձ���
#define     ID_STR_ALARM_TYPE_PARK_TOO_LONG     31023   //ͣ��ʱ���������
#define     ID_STR_ALARM_TYPE_MOTION_DETECT     31024   //�ƶ���ⱨ��
#define     ID_STR_ALARM_TYPE_GPS_SIGNAL_LOSS   31025   //GPSѶ�Ŷ�ʧ����
#define     ID_STR_ALARM_TYPE_LOW_SPEED         31026   //���ٱ��� 
#define     ID_STR_ALARM_TYPE_FENCE_IN		    31027   //�������Χ������ 
#define     ID_STR_ALARM_TYPE_FENCE_OUT		    31028   //������Χ������ 
#define     ID_STR_ALARM_TYPE_FENCE_IN_OVER_SPEED		    31029   //����Χ���ڳ��ٱ��� 
#define     ID_STR_ALARM_TYPE_FENCE_OUT_OVER_SPEED		    31030   //����Χ���ⳬ�ٱ��� 
#define     ID_STR_ALARM_TYPE_FENCE_IN_LOWE_SPEED		    31031   //����Χ���ڵ��ٱ��� 
#define     ID_STR_ALARM_TYPE_FENCE_OUT_LOWE_SPEED		    31032   //����Χ������ٱ��� 
#define     ID_STR_ALARM_TYPE_FENCE_IN_STOP				    31033   //����Χ����ͣ������ 
#define     ID_STR_ALARM_TYPE_FENCE_OUT_STOP				31034   //����Χ����ͣ������
#define     ID_STR_ALARM_TYPE_IN_FENCE		    31035   //����Χ���� 
#define     ID_STR_ALARM_TYPE_OUT_FENCE		    31036   //����Χ���� 
#define     ID_STR_ALARM_TYPE_FIRE		    31037   //��
#define     ID_STR_ALARM_TYPE_PANIC		    31038   //�پ�
#define     ID_STR_ALARM_TYPE_TASK_FINISHED		    31039   //�����������
#define     ID_STR_ALARM_TYPE_IMAGE_UPLOAD		    31040   //ͼƬ�ϴ����
#define		ID_STR_ALARM_TYPE_FLOW_DAY_REMIND		31041	//������Ԥ��
#define		ID_STR_ALARM_TYPE_FLOW_DAY_OVER			31042	//����������
#define		ID_STR_ALARM_TYPE_FLOW_MONTH_REMIND		31043	//������Ԥ��
#define		ID_STR_ALARM_TYPE_FLOW_MONTH_OVER		31044	//����������
#define		ID_STR_ALARM_TYPE_POWER_DOWN			31045	//��ع���
#define		ID_STR_ALARM_TYPE_DOOR_OPEN				31046	//���ſ�
#define		ID_STR_ALARM_TYPE_ZONE_OPEN				31047	//�������
#define		ID_STR_ALARM_TYPE_LOW_BATTERY_VOLTAGE	31048	//��ص�ѹ����
#define		ID_STR_ALARM_TYPE_BATTERY_BAD			31049	//��ػ�
#define		ID_STR_ALARM_TYPE_ENGINE_BAD			31050	//����������

#define		ID_STR_EVENT_INFO_SVR_DISCNT		31051	//���ķ����������жϣ��ͻ��˷���������
#define		ID_STR_EVENT_INFO_SVR_RECNT			31052	//�ɹ���¼���ķ�����
#define		ID_STR_EVENT_INFO_ARMSVR_DISCNT		31053	//���������������жϣ����޷����ձ�����Ϣ
#define		ID_STR_EVENT_INFO_ARMSVR_RECNT		31054	//�ɹ����ӱ���������
#define		ID_STR_EVENT_INFO_USR_CHANGE		31055	//�û���Ϣ�����仯����¼������ʧ�ܣ�
#define		ID_STR_EVENT_INFO_LOAD_FAILED		31056	//���¼�����Ϣʧ�ܣ������µ�¼��������
#define		ID_STR_EVENT_INFO_OPEN_SOUND		31057	//�����������Ŷ���ʧ�ܣ����޷����ű���������
#define		ID_STR_EVENT_INFO_CONFIRM_ALARM		31058	//ȡ���豸[%s]����״̬
#define		ID_STR_EVENT_INFO_PTZ_FAILED		31059	//��̨����ʧ�ܣ�����ԭ��

#define		ID_STR_EVENT_TYPE_SVR_DISCNT		31061	//�����������ж�
#define		ID_STR_EVENT_TYPE_SVR_RECNT			31062	//������ͨ�Żָ�
#define		ID_STR_EVENT_TYPE_ALARM_CHN			31063	//��ͷ��
#define		ID_STR_EVENT_TYPE_FLASH_DEV			31064	//�豸��Ϣ����
#define		ID_STR_EVENT_TYPE_UNKNOW			31065	//δ����
#define		ID_STR_EVENT_TYPE_INFO				31066	//��ʾ��Ϣ
#define		ID_STR_EVENT_TYPE_OVERSPEED			31067	//���ٱ���
#define		ID_STR_EVENT_TYPE_REFUEL			31068	//����
#define		ID_STR_EVENT_TYPE_STILL_FUEL		31069	//��������
#define		ID_STR_EVENT_TYPE_ALARM_OIL_BEGIN	31070	//����ǰ����
#define		ID_STR_EVENT_TYPE_ALARM_OIL_END		31071	//�����ͺ�����


#define		ID_STR_DESC_USEDEFINE				31101	//�������: %d������Դ: %s����������: %s
#define		ID_STR_DESC_URGENCY_BUTTON			31102	//��ť���: %d������: %s
#define		ID_STR_DESC_SHAKE					31103	//
#define		ID_STR_DESC_DOOR_FORNT				31104	//ǰ��
#define		ID_STR_DESC_DOOR_MIDDLE				31105	//����
#define		ID_STR_DESC_DOOR_BACK				31106	//����
#define		ID_STR_DESC_TEMP_LOWEST				31107	//����¶�
#define		ID_STR_DESC_TEMP_HIGHTEST			31108	//����¶�
#define		ID_STR_DESC_DISK_ERROR				31109	//Ӳ�̺�: %d����������: %s
#define		ID_STR_DESC_SPEED_ALARM				31110	//�����ٶ�
#define		ID_STR_DESC_SPEED_LOWEST			31111	//����ٶ�
#define		ID_STR_DESC_SPEED_HIGHTEST			31112	//����ٶ�
#define		ID_STR_DESC_SPEED_TIME				31113	//����ʱ��
#define		ID_STR_DESC_BEYOND_BOUNDS_INT		31114	//ʻ�뱨��
#define		ID_STR_DESC_BEYOND_BOUNDS_OUT		31115	//ʻ������
#define		ID_STR_DESC_BEYOND_BOUNDS_NO		31116	//Χ����
#define		ID_STR_DESC_DOOR_ABNORMAL_1			31117	//����վδͣ������
#define		ID_STR_DESC_DOOR_ABNORMAL_2			31118	//����վ����δ�س���
#define		ID_STR_DESC_DOOR_ABNORMAL_3			31119	//��δ��վ������
#define     ID_STR_DESC_REAL_TEMP               31120   //ʵʱ�¶�



#define		ID_STR_DLG_RELOGIN_TITLE			32001	//Ŀ¼������ͨ���ж�
#define		ID_STR_DLG_RELOGIN_ST_TIP			32002	//�������µ�¼��ȴ�
#define		ID_STR_DLG_RELOGIN_CANCEL			32003	//�˳�ϵͳ
#define		ID_STR_DLG_RELOGIN_BTN_CHANGE		32004	//�л��û�

#define		ID_STR_MENU_SYS						33001	//ϵͳ
#define		ID_STR_MENU_SYS_EXIT				33002	//ϵͳ�˳�
#define		ID_STR_MENU_VIEW					33003	//��ͼ
#define		ID_STR_MENU_MGR						33008	//����
#define		ID_STR_MENU_MGR_USR					33009	//�û�����
#define		ID_STR_MENU_MGR_DEV					33010	//�豸����
#define		ID_STR_MENU_MGR_MSVR				33011	//��ý�����������
#define		ID_STR_MENU_MGR_MSVR_TRAN			33012	//ת�����ù���
#define		ID_STR_MENU_MGR_RECSVR				33013	//¼�����������
#define		ID_STR_MENU_MGR_REC_POS				33014	//¼��洢����
#define		ID_STR_MENU_MGR_ARMSVR				33015	//��������������
#define		ID_STR_MENU_MGR_PREVIEW				33016	//Ԥ������
#define		ID_STR_MENU_MGR_RECPLAN				33017	//¼��ƻ�����
#define		ID_STR_MENU_MGR_ARMACTION			33018	//������������
#define		ID_STR_MENU_HELP					33019	//����
#define		ID_STR_MENU_HELP_ABOUT				33020	//����
#define		ID_STR_MENU_LOG_ALARM				33021	//������־��ѯ
#define		ID_STR_MENU_LOG_USR					33022	//�û���־��ѯ
#define		ID_STR_MENU_TOOL					33023	//����
#define		ID_STR_MENU_BAR						33024	//�˵���
#define		ID_STR_PANE_BAR						33025	//��׼������
#define		ID_STR_VIEW_BAR						33026	//��Ƶ���ڹ�����
#define		ID_STR_FULL_BAR						33027	//ȫ��
#define		ID_STR_SKIN_BAR						33028	//���
#define		ID_STR_MENU_FULLSCREEN				33029	//ȫ��
#define		ID_STR_MENU_VOLUME					33030	//����
#define		ID_STR_MENU_SNAP_DEV				33031	//ǰ��ץ��
#define		ID_STR_MENU_MGR_SYSTEM				33032	//ϵͳ����
#define		ID_STR_MENU_ALARM					33033	//δȷ�ϱ���
#define		ID_STR_OTHER_BAR					33034	//����
#define     ID_STR_MENU_VIDEO_RECORD			33035	//¼������
#define     ID_STR_MENU_MOD_PWD_CUSS            33036   //�޸�����ɹ�
#define     ID_STR_MENU_OLD_PWD     			33037	//�������������
#define     ID_STR_MENU_MOD_PWD_OK              33038   //��������������벻һ�£�����������!
#define     ID_STR_OLD_PWD                      33039   //������
#define     ID_STR_NEW_PWD                      33040   //������
#define     ID_STR_NEW_PWD_OK                   33041   //����ȷ������
#define     ID_STR_TIP_FOR                      33042   //�޸�����
#define     ID_STR_NEW_PWD_EMPTY_WARN           33043   //�����벻��Ϊ�գ�������������!
#define     ID_STR_NEW_OK_PWD_EMPTY_WARN        33044   //ȷ�������벻��Ϊ�գ�������ȷ��������!
#define     ID_STR_OLD_PWD_EMPTY_WARN           33045   //�����벻��Ϊ�գ������������!
#define     ID_STR_OLD_PWD_LEN_WARN             33046   //���������볤��Ϊ%d~%dλ!
#define     ID_STR_NEW_PWD_LEN_WARN             33047   //�����볤��Ϊ%d~%dλ!
#define     ID_STR_OK_NEW_PWD_LEN_WARN          33048   //ȷ�����볤��Ϊ%d~%dλ!
#define     ID_STR_LEN_TIP                      33049   //(4~16λ)
#define		ID_STR_NOT_MODIFY_PSW				33050	//��ǰΪ�����û�,�����޸�����.

#define		ID_STR_PROMPT_MENU_SYS_EXIT			33051	//�˳�CMS�ͻ�������\n�˳�
#define		ID_STR_PROMPT_MENU_NAVIGATE			33052	//��ʾ�������Խ�����ͷ�������\n����
#define		ID_STR_PROMPT_MENU_PANE_PLAY		33053	//��ʾ¼�����������ء��ط����\n����
#define		ID_STR_PROMPT_MENU_VIEW_MAP			33054	//ͬʱ��ʾ��ͼ����Ƶ���沼��\n��ͼ����Ƶ���沼��
#define		ID_STR_PROMPT_MENU_PANE_MAP			33055	//������ʾ��ͼ���沼��\n��ͼ���沼��
#define		ID_STR_PROMPT_MENU_PANE_VIEW		33056	//������ʾ��Ƶ���沼��\n��Ƶ���沼��
#define		ID_STR_PROMPT_MENU_VIEW_POP			33057	//������ʽ��ʾ��Ƶ����\n������Ƶ����
#define		ID_STR_PROMPT_MENU_EVENT			33058	//��ʾ���������¼����\n�¼����
#define		ID_STR_PROMPT_MENU_MGR_PREVIEW		33059	//��Ƶ������ѯ����\n��ѯ����
#define		ID_STR_PROMPT_MENU_MGR_ARMACTION	33060	//����������������\n������������
#define		ID_STR_PROMPT_MENU_LOG_ALARM		33061	//��ѯ������ʷ�����¼�\n������־��ѯ
#define		ID_STR_PROMPT_MENU_LOG_USR			33062	//��ѯ�û���ʷ������־\n�û���־��ѯ
#define		ID_STR_PROMPT_MENU_ABOUT			33063	//��ʾ������Ϣ���汾\n����Cms Client
#define		ID_STR_PROMPT_MENU_FULLSCREEN		33064	//ȫ����ʾ
#define		ID_STR_PROMPT_MENU_SKIN				33065	//ѡ����Ƥ��
#define		ID_STR_PROMPT_MENU_SKIN_VISTA_BLUE	33066	//Vista Blue
#define		ID_STR_PROMPT_MENU_SKIN_VISTA_BLACK	33067	//Vista Black
#define		ID_STR_PROMPT_MENU_SKIN_SYSTEM		33068	//System
#define		ID_STR_PROMPT_MENU_VIEW_UP			33069	//�����ƶ���Ƶ����
#define		ID_STR_PROMPT_MENU_VIEW_DOWN		33070	//�����ƶ���Ƶ����
#define		ID_STR_PROMPT_MENU_VIEW_1			33071	//1������ʾ��Ƶ����
#define		ID_STR_PROMPT_MENU_VIEW_4			33072	//4������ʾ��Ƶ����
#define		ID_STR_PROMPT_MENU_VIEW_9			33073	//9������ʾ��Ƶ����
#define		ID_STR_PROMPT_MENU_VIEW_16			33074	//16������ʾ��Ƶ����
#define		ID_STR_PROMPT_MENU_OPEN_SOUND		33075	//�򿪽�����Ƶ���������
#define		ID_STR_PROMPT_MENU_CLOSE_SOUND		33076	//�ر�����
#define		ID_STR_PROMPT_MENU_OPEN_DUE			33077	//�뽹����Ƶ������豸���������Խ�
#define		ID_STR_PROMPT_MENU_CLOSE_DUE		33078	//ֹͣ������Ƶ����������Խ�
#define		ID_STR_PROMPT_MENU_VOLUME			33079	//����������С
#define		ID_STR_PROMPT_MENU_SNAP_DEV			33080	//ʵʱ���豸ǰ��ץ��ͼƬ
#define		ID_STR_PROMPT_MENU_MGR_SYSTEM		33081	//�ͻ���ϵͳ��������
#define		ID_STR_PROMPT_MENU_ALARM			33082	//��ѯδȷ�ϵı�����Ϣ
#define		ID_STR_PROMPT_MENU_LAYOUT_1			33083	//���沼��1
#define		ID_STR_PROMPT_MENU_LAYOUT_2			33084	//���沼��2
#define		ID_STR_PROMPT_MENU_LAYOUT_3			33085	//���沼��3
#define		ID_STR_PROMPT_MENU_LAYOUT_4			33086	//���沼��4
#define		ID_STR_PROMPT_MENU_LAYOUT_5			33087	//���沼��5
#define		ID_STR_PROMPT_MENU_LAYOUT_6			33088	//���沼��6
#define		ID_STR_PROMPT_MENU_LAYOUT_7			33089	//���沼��7
#define		ID_STR_PROMPT_MENU_LAYOUT_8			33090	//���沼��8
#define		ID_STR_LAYOUT_1						33091	//��ʾ���沼��1
#define		ID_STR_LAYOUT_2						33092	//��ʾ���沼��2
#define		ID_STR_LAYOUT_3						33093	//��ʾ���沼��3
#define		ID_STR_LAYOUT_4						33094	//��ʾ���沼��4
#define		ID_STR_LAYOUT_5						33095	//��ʾ���沼��5
#define		ID_STR_LAYOUT_6						33096	//��ʾ���沼��6
#define		ID_STR_LAYOUT_7						33097	//��ʾ���沼��7
#define		ID_STR_LAYOUT_8						33098	//��ʾ���沼��8
#define		ID_STR_PROMPT_MENU_MAP_VIEW			33099	//��ͼ/��Ƶ
#define		ID_STR_TOOLTIP_NAVIGATE				33100	//��ʾ�����б����
#define		ID_STR_TOOLTIP_PLAY					33101	//��ʾ¼���������������
#define		ID_STR_CAM_PTZ						33102	//��̨
#define		ID_STR_CAM_COLOR					33103	//��ɫ
#define		ID_STR_PROMPT_MENU_AV_START			33104	//������Ƶ
#define		ID_STR_PROMPT_MENU_AV_STOP			33105	//ֹͣ��Ƶ
#define		ID_STR_PROMPT_MENU_AV_START_ALL		33106	//����������Ƶ
#define		ID_STR_PROMPT_MENU_AV_STOP_ALL		33107	//ֹͣ������Ƶ
#define		ID_STR_PROMPT_MENU_AV_CLEAR			33108	//�������
#define		ID_STR_PROMPT_MENU_AV_CLEAR_ALL		33109	//�����������
#define		ID_STR_PROMPT_MENU_PANE_TRACK		33110	//��ʾ�켣�������ط����\n�켣
#define		ID_STR_TOOLTIP_TRACK				33111	//��ʾ�����������ط����
#define		ID_STR_PROMPT_MENU_MGR_VIDEOREC		33112	//�ͻ���¼���������
#define		ID_STR_PROMPT_MENU_OPEN_CMDSEND		33113	//����Ϣ

#define		ID_STR_DLG_ARMTIP_TITLE				34001	//������ʾ
#define		ID_STR_DLG_ARMTIP_ST_DEV			34002	//��ط�����
#define		ID_STR_DLG_ARMTIP_ST_TYPE			34003	//��������
#define		ID_STR_DLG_ARMTIP_ST_TIME			34004	//����ʱ��
#define		ID_STR_DLG_ARMTIP_ST_DESC			34005	//��������
#define		ID_STR_DLG_ARMTIP_BTN_MORE			34006	//����
#define		ID_STR_DLG_ARMTIP_BTN_PREV			34007	//��һ��
#define		ID_STR_DLG_ARMTIP_BTN_NEXT			34008	//��һ��
#define		ID_STR_DLG_ARMTIP_BTN_MAP			34009	//��ͼ��ʾ
#define		ID_STR_DLG_ARMTIP_ST_DEALPLAN		34010   //��������
#define		ID_STR_DLG_ARMTIP_ST_DEALALARM		34011   //��������
#define		ID_STR_DLG_ARMTIP_BTN_DEALALARM		34012   //��������
#define		ID_STR_DLG_ARMTIP_DEALALARM_TIP		34013	//�������ݲ��ܴ���128���ַ�����ȷ�ϣ�
#define     ID_STR_DLG_ARMTIP_ALARM_DEAL_STA	34014	//��������״̬
#define     ID_STR_DLG_ARMTIP_ALARM_NOCONFIRM	34015	//����δ����
#define     ID_STR_DLG_ARMTIP_ALARM_CONFIRMED	34016	//�����Ѿ�����
#define		ID_STR_DLG_ARMTIP_ALARM_NONEED		34017	//���账��		
#define		ID_STR_DLG_ARMTIP_ALARM_TREATMENT	34018	//��������
#define		ID_STR_DLG_ARMTIP_ALARM_TREATTIME	34019	//����ʱ��
#define		ID_STR_DLG_ARMTIP_ALARM_TREATUSER	34020	//�����û�
#define		ID_STR_DLG_ARMTIP_ALARM_LANGANDLAT	34021	//��γ��
#define		ID_STR_DLG_ARMTIP_TITLE_ALL			34022	//δ��������
#define     ID_STR_DLG_ARMTIP_ST_SELECT_VEH		34023	//ѡ����
#define		ID_STR_DLG_ARMTIP_ST_HANDLING_STA	34024	//����״̬
#define		ID_STR_DLG_ARMTIP_TITLE_ARM_LOG		34025	//������־����
#define		ID_STR_DLG_ARMTI_HANDLE_FAILED		34026   //����ʧ��
#define		ID_STR_DLG_ARMTI_DEV_CONTROL		34027   //��������

#define		ID_STR_DLG_LOG_QUERY_TITLE			35001	//��־��ѯ
#define		ID_STR_DLG_LOG_ALARM_TITLE			35002	//������־��ѯ
#define		ID_STR_DLG_LOG_USR_TITLE			35003	//�û���־��ѯ
#define		ID_STR_DLG_LOG_ARM_ST_TYPE			35004	//��������
#define		ID_STR_DLG_LOG_ARM_ST_TIME_BEG		35005	//��ʼʱ��
#define		ID_STR_DLG_LOG_ARM_ST_TIME_END		35006	//����ʱ��
#define		ID_STR_DLG_LOG_ARM_BTN_QUERY		35007	//��ѯ
#define		ID_STR_DLG_LOG_ARM_ALL				35008	//���б���
#define		ID_STR_DLG_LOG_ARM_TIME_ERR			35009	//������ʼʱ�����С�ڽ���ʱ�䣬���������룡
#define		ID_STR_DLG_LOG_ARM_DEV_ERR			35010	//��ѡ���ѯ���豸��
#define		ID_STR_DLG_LOG_QUERY_FAILED			35011	//��ѯʧ�ܣ�����ԭ��
#define		ID_STR_DLG_LOG_ARM_CONFIRM_TYPE		35012   //�ֶ�ȷ�ϱ�������
#define		ID_STR_DLG_LOG_ARM_AFFIRM_ALL		35013	//�ֶ�ȷ��ȫ��
#define		ID_STR_DLG_LOG_ARM_AFFIRM_NO		35014   //û���ֶ�ȷ�ϵ�
#define		ID_STR_DLG_LOG_ARM_AFFIRM_OK		35015	//�Ѿ��ֶ�ȷ�ϵı���
#define		ID_STR_DLG_LOG_ARM_BTN_EXPROT		35016   //����Exsle��
#define		ID_STR_DLG_LOG_EXCEL_TABLE_NM		35017	//Exsetl������
#define		ID_STR_DLG_LOG_ARM_TIP_TITEL		35018   //��ʾ:
#define		ID_STR_DLG_LOG_ARM_TIP_TEXT			35019	//��ɫ-���账��,��ɫ-�账������ɫ-�Ѵ���
#define		ID_STR_DLG_LOG_BTN_STOP_QUERY		35020   //ֹͣ��ѯ
#define		ID_STR_DLG_LOG_SHOW_PAGE      		35021	//ÿҳ��ʾ%d,��ǰΪ%dҳ
#define		ID_STR_DLG_LOG_WAITE_FOR     		35022   //���ڻ�ȡ�û���Ϣ����ȴ�......
#define		ID_STR_DLG_LOG_INFO_FAIL_GET		35023	//��ȡ�û���Ϣʧ��
#define		ID_STR_DLG_LOG_INFO_SUCC_GET		35024   //��ȡ�û���Ϣ�ɹ�

#define		ID_STR_EXCEL_EXPT_FILEDLG_TITLE		35051	//����Excel��	
#define		ID_STR_EXCEL_EXPT_TIP_NODIRVER		35052	//û�а�װExcel!\n���Ȱ�װExcel��������ʹ�õ�������!
#define		ID_STR_EXCEL_EXPT_TIP_SUCCEED		35053	//�����ļ�������
#define		ID_STR_EXCEL_EXPT_TIP_OV_FAILED		35054	//�����ļ�ʱ������
#define     ID_STR_EXCEL_EXPT_FILTER			35055   //Excel�ļ�(*.xls)

#define		ID_STR_DLG_LOG_USR_ST_LOG			35101	//ϵͳ�û�
#define		ID_STR_DLG_LOG_USR_LST_USR			35102	//�û�
#define		ID_STR_DLG_LOG_USR_ALL_USR			35103	//�����û�
#define		ID_STR_USER_NO_PRIVILEGE			35104	//��ǰ�û��޴�Ȩ��

#define		ID_STR_LOG_TYPE_LOGIN				35201	//�û���¼
#define		ID_STR_LOG_TYPE_MGR_DEV				35202	//�豸����
#define		ID_STR_LOG_TYPE_MGR_USR				35203	//�û�����
#define		ID_STR_LOG_TYPE_MGR_MAP				35204	//��ͼ����
#define		ID_STR_LOG_TYPE_MEIDA_SVR			35205	//��ý�����������
#define		ID_STR_LOG_TYPE_RECORD_SVR			35206	//¼�����������
#define		ID_STR_LOG_TYPE_REC_PLAN			35207	//¼��ƻ�����
#define		ID_STR_LOG_TYPE_MDEV_TRAN			35208	//��ý��ת������
#define		ID_STR_LOG_TYPE_REC_POS				35209	//�豸�洢����
#define		ID_STR_LOG_TYPE_ALARM_SVR			35210	//��������������
#define		ID_STR_LOG_TYPE_MATRIX				35211	//����ǽ����
#define		ID_STR_LOG_TYPE_UNKNOW				35212	//δ֪

#define		ID_STR_DLG_ARM_LAST_TITLE			36001	//�鿴δȷ�ϱ���
#define		ID_STR_DLG_ARM_LAST_BTN_QUERY		36002	//��ѯ���౨��
#define		ID_STR_DLG_ARM_LAST_BTN_CONFRIM		36003	//ȷ�ϱ���
#define		ID_STR_DLG_ARM_LAST_ST_DEV			36004	//ѡ����
#define		ID_STR_DLG_ARM_LAST_BTN_REFRESH		36005	//ˢ�±���

#define		ID_STR_PTZ_ZOOM_ADD					37001	//����ǰ��
#define		ID_STR_PTZ_ZOOM_DEL					37002	//������
#define		ID_STR_PTZ_FOCUS_ADD				37003	//������
#define		ID_STR_PTZ_FOCUS_DEL				37004	//�����С
#define		ID_STR_PTZ_LIGHT_ADD				37005	//��Ȧ�Ŵ�
#define		ID_STR_PTZ_LIGHT_DEL				37006	//��Ȧ��С
#define		ID_STR_PTZ_LIGHT_ON					37007	//�򿪵ƹ�
#define		ID_STR_PTZ_LIGHT_OFF				37008	//�رյƹ�
#define		ID_STR_PTZ_WIPER_ON					37009	//����ˢ
#define		ID_STR_PTZ_WIPER_OFF				37010	//�ر���ˢ
#define		ID_STR_PTZ_PRESET_NEXT				37011	//��һҳ
#define		ID_STR_PTZ_PRESET_PREV				37012	//��һҳ
#define		ID_STR_PTZ_TOP						37013	//��
#define		ID_STR_PTZ_LEFT_TOP					37014	//����
#define		ID_STR_PTZ_RIGHT_TOP				37015	//����
#define		ID_STR_PTZ_LEFT						37016	//��
#define		ID_STR_PTZ_RIGHT					37017	//��
#define		ID_STR_PTZ_LEFT_BOTTOM				37018	//����
#define		ID_STR_PTZ_RIGHT_BOTTOM				37019	//����
#define		ID_STR_PTZ_BOTTOM					37020	//��
#define		ID_STR_PTZ_AUTO_CRUISE				37021	//�Զ�Ѳ��
#define		ID_STR_PTZ_PRESET_MOVE				37022	//����
#define		ID_STR_PTZ_PRESET_SET				37023	//����
#define		ID_STR_PTZ_PRESET_DEL				37024	//ɾ��
#define		ID_STR_PTZ_TIP_PRESET_MOVE			37025	//����Ԥ�õ�
#define		ID_STR_PTZ_TIP_PRESET_SET			37026	//����Ԥ�õ�
#define		ID_STR_PTZ_TIP_PRESET_DEL			37027	//ɾ��Ԥ�õ�
#define		ID_STR_PTZ_ZOOM						37028	//�䱶
#define		ID_STR_PTZ_FOCUS					37029	//����
#define		ID_STR_PTZ_LIGHT					37030	//��Ȧ
#define		ID_STR_PTZ_NO_PREVIEW_TIP			37031	//��ѡ��ʵʱԤ�����ں���ִ����̨������


#define		ID_STR_COLOR_BRI					38001	//����
#define		ID_STR_COLOR_CON					38002	//�Աȶ�
#define		ID_STR_COLOR_HUE					38003	//ɫ��
#define		ID_STR_COLOR_SAT					38004	//���϶�
#define		ID_STR_COLOR_DEFAULT				38005	//Ĭ��

#define		ID_STR_DLG_SYSTEM_TITLE				39001	//ϵͳ����
#define		ID_STR_DLG_SYSTEM_ST_SYS			39002	//ϵͳ����
#define		ID_STR_DLG_SYSTEM_ST_LANG			39003	//ϵͳ����
#define		ID_STR_DLG_SYSTEM_ST_VIEW			39004	//��Ƶ����
#define		ID_STR_DLG_SYSTEM_ST_VIEW_SIZE		39005	//��ʾ����
#define		ID_STR_DLG_SYSTEM_ST_VIEW_MODE		39006	//��ʾģʽ
#define		ID_STR_DLG_SYSTEM_ST_PATH			39007	//·������
#define		ID_STR_DLG_SYSTEM_ST_FILE_DOWN		39008	//�ļ�����
#define		ID_STR_DLG_SYSTEM_ST_PIC_CAPTURE	39009	//ͼƬץ��
#define		ID_STR_DLG_SYSTEM_BTN_BROWSE		39010	//���
#define		ID_STR_DLG_SYSTEM_BTN_SAVE			39011	//����
#define		ID_STR_DLG_SYSTEM_BTN_TIP_SUC		39012	//����ɹ�
#define		ID_STR_DLG_SYSTEM_BTN_TIP_REBOOT	39013	//����ɹ������Բ�������ͼ���ͻ��߽�����ı���Ҫ������Ч��
#define		ID_STR_DLG_SYSTEM_VEHI_COUNT_TIP	39014	//��ͼ��������ʾ������Ŀ������%d-%d֮�䣬���������룡
#define		ID_STR_DLG_SYSTEM_ST_MAP			39015	//��ͼ����
#define		ID_STR_DLG_SYSTEM_ST_MAP_TYPE		39016	//��ͼ����
#define		ID_STR_DLG_SYSTEM_ST_VEHI_COUNT		39017	//��ͼ������Ŀ
#define		ID_STR_DLG_SYSTEM_ST_CNT_MODE		39018	//����ģʽ
#define		ID_STR_DLG_SYSTEM_CHK_MAP_GPSFIX	39019	//GPSУ��
#define		ID_STR_DLG_SYSTEM_ST_DELAY_TIME		39020	//��Ƶ����ʱ��
#define		ID_STR_DLG_SYSTEM_ST_TIME_UINT		39021	//��λ����
#define		ID_STR_DLG_SYSTEM_DELAY_TIME_TIP	39022	//��Ƶ����ʱ�������%d-%d֮�䣬���������룡
#define		ID_STR_DLG_SYSTEM_TIME_COMPARE_TIP	39023	//��Ƶ������Сʱ�䲻�ô������ʱ�䣬���������룡
#define		ID_STR_DLG_SYSTEM_ST_ARM			39024	//��������
#define		ID_STR_DLG_SYSTEM_ST_ARM_COUNT		39025	//δ����������Ŀ
#define     ID_STR_DLG_SYSTEM_ARM_COUNT_TIP		39026   //������Ŀ������%d-%d֮�䣬���������룡
#define		ID_STR_DLG_SYSTEM_ST_DDRAW_RGB16	39027   //Direct Draw ��Ƶ
#define		ID_STR_DLG_SYSTEM_CHK_DDRAW_RGB16	39028	//ʹ��RGB16��ʽ
#define		ID_STR_DLG_SYSTEM_LESS_VEHI_TIP		39029	//��ͼ��������ʾ������ĿС�ڵ�ǰ��ͼ��س�����Ŀ�����������룡
#define		ID_STR_DLG_SYSTEM_ALARM_SHUT 		39030	//������Ƶ�Զ��ر�ʱ�������%d-%d֮�䣬����������!
#define     ID_STR_DLG_SYSTEM_CK_AUTO_SHUT      39031   //������Ƶ�Զ��ر� IDC_CHECK_ALARM_CLOSE  
#define     ID_STR_DLG_SYSTEM_SHUT_TIME         39032   //��Ƶ�ر�ʱ��
#define     ID_STR_DLG_SYSTEM_KMH               39033   //ǧ��/ʱ
#define     ID_STR_DLG_SYSTEM_MPH               39034   //Ӣ��/ʱ
#define     ID_STR_DLG_SYSTEM_SPEED_UNIT        39035   //�ٶȵ�λ
#define     ID_STR_DLG_STSTEM_UNIT_MP           39036   //Ӣ��
#define     ID_STR_DLG_STSTEM_UNIT_KM           39037   //ǧ��
#define     ID_STR_DLG_STSTEM_POLLING_WARN      39038   //��ѯʱ�����%d-%d֮��!
#define     ID_STR_DLG_SYSTEM_AUTO_CLOSE_VIDEO  39039   //%���Ӻ��Զ��ر���Ƶ
#define     ID_STR_DLG_SYSTEM_NOT_CLOSE_VIDEO   39040   //���Զ��ر���Ƶ
#define     ID_STR_DLG_SYSTEM_SETTING_CLOSE     39041   //�ر���Ƶ����
#define     ID_STR_DLG_SYSTEM_CLOSE_TIP         39042   //�ͻ����޲����������
#define     ID_STR_DLG_SYSTEM_CLOSE_VIEW        39043   //������ƵԤ����
#define     ID_STR_DLG_SYSTEM_TRY_TIP           39044   //��Ƶ��Ԥ��ʱ,�ɳ��Թ�ѡ����!
#define     ID_STR_DLG_SYSTEM_GOOGLE_SPEED      39045   //Google���ʼ���
#define     ID_STR_DLG_SYSTEM_GOOGLE_SPEED_CK   39046   //�Ƿ�����Goole��ͼ���ʼ���
#define		ID_STR_DLG_SYSTEM_AUTO_CLOSE_VOICE	39047	//�رնԽ��ͼ���
#define		ID_STR_DLG_SYSTEM_CLOSE_VOICE		39048	//�򿪶Խ��ͼ�����
#define     ID_STR_DLG_SYSTEM_UI_STYLE_DEFAULT  39049   //Ĭ��(����)
#define     ID_STR_DLG_SYSTEM_UI_STYLE_BLUE     39050   //����
#define     ID_STR_DLG_SYSTEM_UI_STYLE		    39051   //������
#define     ID_STR_DLG_SYSTEM_AUTO_LOGIN		39052   //���������Զ���¼
#define     ID_STR_DLG_SYSTEM_DEFUALT_VIDEO		39053   //Ĭ��������Ƶ


#define		ID_STR_VIEW_MODE_REAL				39501	//ʵʱ�Ժ�
#define		ID_STR_VIEW_MODE_SMOOTH				39502	//�����Ժ�
#define		ID_STR_VIEW_SIZE_FULL				39503	//ȫ����ʾ
#define		ID_STR_VIEW_SIZE_4_3				39504	//4 : 3
#define		ID_STR_VIEW_SIZE_16_9				39505	//16 : 9
#define		ID_STR_VIEW_MAP_GOOGLE				39506	//Google
#define		ID_STR_VIEW_MAP_MAPINFO				39507	//Mapinfo
#define		ID_STR_VIEW_MODE					39508	//��Ƶģʽ
#define		ID_STR_VIEW_SIZE					39509	//��Ƶ����
#define		ID_STR_VIEW_SIZE_PROMPT				39510	//��Ƶ��������
#define		ID_STR_VIEW_MODE_CAPTION			39511	//ģʽ
#define		ID_STR_DEV_PROMPT_TRACE				39512	//ʵʱ��س���״̬
#define		ID_STR_DEV_PROMPT_SETUP				39514	//�豸��������
#define		ID_STR_DEV_SETUP					39515	//������������
#define		ID_STR_DEV_TRACE					39516	//ʵʱ���
#define		ID_STR_CNT_MODE_TCP					39517	//Tcp����
#define		ID_STR_CNT_MODE_UDP					39518	//Udp����
#define     ID_STR_VIEW_MAP_GOOGLE_CHINA        39519   //Google�й�
#define     ID_STR_VIDEO_POLLING_TIME           39520   //��ѯʱ��
#define     ID_STR_VIEW_MAP_BAIDU		        39521   //�ٶ�


#define		ID_STR_DLG_GPS_RECORD_TITLE			39550	//�켣�ط���ʷ��¼
#define		ID_STR_DLG_GPS_RECORD_DOWM_TIME		39551	//����ʱ��

#define		ID_STR_DLG_TRACK_TMP				39600	//�¶�
#define		ID_STR_DLG_TRACK_ST_DEVICE			39601	//�����豸
#define		ID_STR_DLG_TRACK_BTN_SELECT			39602   //ѡ����
#define		ID_STR_DLG_TRACK_ST_SEARCH_TM		39603   //����ʱ��
#define		ID_STR_DLG_TRACK_ST_SEARCH_TMTO		39604	//ʱ����
#define		ID_STR_DLG_TRACK_BTN_PLAY			39605	//�켣����
#define     ID_STR_DLG_TRACK_BTN_PAUSE			39606	//�켣��ͣ
#define		ID_STR_DLG_TRACK_BTN_CONTINUE		39607	//�켣����
#define		ID_STR_DLG_TRACK_BTN_STOP			39608	//�켣ֹͣ
#define     ID_STR_DLG_TRACK_BTN_DEL			39609	//�켣ɾ��
#define		ID_STR_DLG_TRACK_ST_TRACK_SPD		39610   //�ط��ٶ�
#define		ID_STR_DLG_TRACK_ST_SPD_UT			39611   //�طŵ�λ
#define		ID_STR_DLG_TRACK_ST_CUR_DEV			39612   //��ǰ����
#define		ID_STR_DLG_TRACK_ST_BEG_TIME		39613	//GPS��ʼʱ��
#define     ID_STR_DLG_TRACK_ST_END_TIME		39614   //GPS����ʱ��
#define     ID_STR_DLG_TRACK_ST_CUR_TIME		39615   //GPS��ǰʱ��
#define		ID_STR_DLG_TRACK_ST_GPS_LONG		39616	//GPS����
#define		ID_STR_DLG_TRACK_ST_GPS_LAT			39617	//GPSγ��
#define     ID_STR_DLG_TRACK_ST_DEV_SPD			39618	//�����ٶ�
#define		ID_STR_DLG_TRACK_ST_DEV_TMP			39619	//�����¶�
#define     ID_STR_DLG_TRACK_ARM_FAIL_REAS		39620	//ʧ��ԭ��
#define		ID_STR_DLG_TRACK_ARM_NO_TRACK		39621	//�ҵ��켣
#define     ID_STR_DLG_TRACK_ARM_DEL_TRACK		39622	//ɾ���켣
#define		ID_STR_DLG_TRACK_BTN_CENTER_VEH		39623   //���г���
#define     ID_STR_DLG_TRACK_TIP_TITLE			39624	//��ʾ:
#define		ID_STR_DLG_TRACK_TIP_TEXT			39625	//ÿ%s�벥��һ��GPS����
#define		ID_STR_DLG_TRACK_RESEARCH_TIP		39626   //��ǰ���ڲ��ţ�ȷ������������
#define		ID_STR_DLG_TRACK_SEL_DEV_EMPTY		39627	//��ѡ��һ��������㣡
#define		ID_STR_DLG_TRACK_TEMPER_SYMBOL		39628	//��
#define		ID_STR_DLG_TRACK_FAIL       		39629	//ʧ��ԭ��
#define     ID_STR_DLG_TRACK_PLAY               39630   //�켣�ط�
#define     ID_STR_DLG_TRACK_LICHENG            39631   //���
#define     ID_STR_DLG_TRACK_TIME_WARN          39632   //��ֹʱӦ�ô�����ʼʱ��
#define     ID_STR_DLG_TRACK_DAY_COUNT_WARN     39633   //��ȷ����ѯ�Ĺ켣������������ڵ���ʷ�켣!

#define     ID_STR_DLG_TRACK_PARKING_V          39634   //ͣ��%d��
#define     ID_STR_DLG_TRACK_NORMAL_FINISH      39635   //�����ط����!
#define     ID_STR_DLG_TRACK_CONTRAST_FINISH    39636   //�ԱȻط����!             
#define     ID_STR_DLG_TRACK_CONTRAST_WARN      39637   //�ԱȻط�����ܻط�3��!
#define     ID_STR_DLG_TRACK_NORMAL_AGAIN       39638   //�Ƿ�Ҫ�������������طŹ켣?
#define     ID_STR_DLG_TRACK_FAST_AGAIN         39639   //�Ƿ�Ҫ�����������ٻطŹ켣?   
#define     ID_STR_DLG_TRACK_CONTRAST_WARN_TEL  39640   //�켣�ԱȲ��ܳ���3��,�Ƿ�Ҫ���¿�ʼ�ط�?
#define     ID_STR_DLG_TRACK_TYPE               39641   //�ط�����
#define     ID_STR_DLG_TRACK_TYPE_SHOW_GPS      39642   //����ʾ�����¼�
#define     ID_STR_DLG_TRACK_TYPE_SHOW_ALAR_GPS 39643   //��ʾ�����¼�
#define     ID_STR_DLG_TRACK_TYPE_SHOW_ALARM    39644   //ֻ��ʾ�����¼�
#define     ID_STR_DLG_TRACK_DESCRIB            39645   //����
#define     ID_STR_DLG_TRACK_NORMAL             39646   //�����ط�
#define     ID_STR_DLG_TRACK_FAST               39647   //���ٻط�
#define     ID_STR_DLG_TRACK_CONTRAST           39648   //�ԱȻط�
#define     ID_STR_DLG_TRACK_INDEX              39649   //���
#define     ID_STR_DLG_TRACK_FANGXIANG          39650   //����

#define		ID_STR_DLG_EXPIRED_TITLE			39651	//������ʾ
#define		ID_STR_DLG_EXPIRED_TIP_EXPIRED		39652	//�ͻ����ѹ���
#define		ID_STR_DLG_EXPIRED_TIP_TIMELEFT		39653   //��ʾʣ��ʱ��%d
#define		ID_STR_DLG_EXPIRED_TBACK_TITLE		39654	//�Խ�����
#define		ID_STR_DLG_EXPIRED_TBACK_RQUE		39655	//����Խ�
#define		ID_STR_DLG_EXPIRED_TBACK_ACCEPT		39656	//����
#define		ID_STR_DLG_EXPIRED_TBACK_REFUSE		39657	//�ܾ�
#define     ID_STR_DLG_EXPIRED_USE_TITLE		39658	//�û���Ϣ��ʾ
#define		ID_STR_DLG_EXPIRED_USER_EXPIRED		39659	//�û��ѹ��ڣ�

#define     ID_STR_DLG_TRACK_PROCESS            39660   //  �طŽ���
#define     ID_STR_DLG_TRACK_PARKING_INTERVAL   39661   //  ͣ�����
#define     ID_STR_DLG_TRACK_MINUTE             39662   //  ����
#define     ID_STR_DLG_TRACK_DIS                39663   //  ���  

#define		ID_STR_DLG_TRACK_DECALITRE			39664	//��decalitre
#define		ID_STR_DLG_TRACK_YOULIANG			39665	//����
#define		ID_STR_DLG_TRACK_CONTROL			39666	//�������
#define		ID_STR_DLG_TRACK_TAG_TRACK			39667	//�켣
#define		ID_STR_DLG_TRACK_LICHENG_EX			39668	//ʵʱ���/�����
#define		ID_STR_DLG_TRACK_NO_TRACK_TO_SAVE	39669	//û�й켣���Ա���.


#define		ID_STR_DLG_ABOUT_TITLE				39681	//���� GPSClient
#define		ID_STR_DLG_ABOUT_ST_VERSION			39682	//GPSClient 1.0 ��
#define     ID_STR_DLG_ABOUT_ST_COPYRIGHT		39683	//��Ȩ���� (C) 2010
#define		ID_STR_DLG_ABOUT_ST_EXPIRED			39684   //��ʾʱ��

#define     ID_STR_DLG_ARMVIDEO_TITLE			39690	//������Ƶ

#define		ID_STR_DLG_VIDEOCOVER_TITLE			39701	//Ԥ����ʾ
#define		ID_STR_DLG_VIDEOCOVER_STC_TIP		39702	//�Ƿ��滻��ǰԤ���Ľ��㴰��?
#define		ID_STR_DLG_VIDEOCOVER_CHK_TIP		39703	//�Ժ�����ʾ
#define		ID_STR_DLG_VIDEO_MAX_NUM_TIP		39704	//¼�����Ŀ���ܳ���%d
#define     ID_STR_DLG_VIDEO_WARN_START         39705   //����%s-ͨ��%d����¼��ʼ
#define     ID_STR_DLG_VIDEO_WARN_END           39706   //����%s-ͨ��%d����¼�����
#define     ID_STR_DLG_VIDEO_START              39707   //����¼��ʼ
#define     ID_STR_DLG_VIDEO_RECORDING_TIP      39708   //����¼��,����¼��¼��%d��
#define     ID_STR_DLG_VIDEO_FINISH             39709   //����¼�����
#define     ID_STR_DLG_VIDEO_RECORDED_TIME_TIP  39710   //����¼��¼��ʱ��%d��

//#define		ID_STR_DLG_CMDSEND_TITLE			39711	//TTS����
#define		ID_STR_DLG_CMDSEND_BTN_SEND			39712	//����
#define		ID_STR_DLG_CMDSEND_BTN_CLOSE		39713	//�ر�
#define		ID_STR_DLG_CMDSEND_TEXT_EMPTY		39714	//�������ݲ���Ϊ��,���������룡
#define		ID_STR_DLG_CMDSEND_DEVLIST_EMPTY	39715	//���ͳ����б�����Ϊ��,���������ӣ�
#define		ID_STR_DLG_CMDSEND_TXTE_OVER		39716	//�����������ܳ���%d�ַ�
#define		ID_STR_DLG_CMDSEND_SEND_FAILD		39717	//������Ϣʧ��
#define		ID_STR_DLG_CMDSEND_SEND_LIST		39718	//�����б�		
#define		ID_STR_DLG_CMDSEND_ST_RECORD_WND	39719	//���ͼ�¼
#define		ID_STR_DLG_CMDSEND_ST_SEND_WND		39720	//���ʹ���	
#define		ID_STR_DLG_CMDSEND_BAR_DELDEV		39721   //ɾ��
#define		ID_STR_DLG_CMDSEND_BAR_EMPTYDEV		39722	//���

#define		ID_STR_DLG_DEVUSERINFO_TITLE		39731	//�û���Ϣ
#define		ID_STR_DLG_DEVUSERINFO_CHK_SAVE		39732	//�Ƿ񱣴��û���Ϣ
#define		ID_STR_DLG_DEVUSERINFO_EMPTY_TIP	39733	//�û����������벻��Ϊ��
#define		ID_STR_DLG_DEVUSERINFO_MAXNUM_TIP	39734	//�û����������볤�Ȳ��ܳ���%d���ַ�
#define     ID_STR_DLG_DEVUSERINFO_WARN_TO      39735   //�û����������ֺ���ĸ���
#define     ID_STR_DLG_DEVUSERINFO_TELL_TO      39736   //�Ƿ񽫸��û���Ϣ���õ��������� IDC_CHK_USE_OTHER

#define		ID_STR_CMD_SEND_FAILED				39741	//����ʧ��
#define		ID_STR_CMD_SEND_SUCCESS				39742	//���ͳɹ�
#define		ID_STR_CMD_ERR_NO_RIGHT				39743	//û��Ȩ��

#define		ID_STR_DEV_RECORD_DISK_ERR			39750	//д�ļ��������������Ƿ�����
#define		ID_STR_DEV_RECORD_DISR_NORMAL		39751   //д�ļ�����

#define		ID_STR_DLG_PICPREVIEW_TITLE			39761	//Ԥ��ͼƬ
#define		ID_STR_DLG_PICPREVIEW_BTN_PREV		39762   //ǰһ��
#define		ID_STR_DLG_PICPREVIEW_BTN_NEXT		39763	//��һ��
#define		ID_STR_DLG_PICPREVIEW_BTN_BROWSE	39764	//���
#define		ID_STR_DLG_PICPREVIEW_ST_GO			39765   //��ת��

#define		ID_STR_DLG_PATHSET_TITLE			39771	//·��ѡ��
#define		ID_STR_DLG_PATHSET_ST_FILE_NAME		39772	//�ļ�����
#define		ID_STR_DLG_PATHSET_ST_DOWN_PATH		39773	//����·��
#define		ID_STR_DLG_PATHSET_BTN_BROWSE		39774	//���
#define		ID_STR_DLG_PATHSET_BTN_DOWN			39775	//����	
#define		ID_STR_DLG_PATHSET_SCOURCE_FILENAME	39776	//Դ�ļ�	

#define		ID_STR_DLG_DEVINFO_TITLE			39781	//������Ϣ
#define		ID_STR_DLG_DEVINFO_ST_NAME			39782	//��������
#define		ID_STR_DLG_DEVINFO_ST_ID			39783	//�������
#define		ID_STR_DLG_DEVINFO_ST_NO			39784	//���ƺ�
#define		ID_STR_DLG_DEVINFO_ST_SIM			39785	//SIM
#define		ID_STR_DLG_DEVINFO_ST_BRAND			39786	//����Ʒ��
#define		ID_STR_DLG_DEVINFO_ST_COLOR			39787	//������ɫ
#define		ID_STR_DLG_DEVINFO_ST_NOTYPE		39788	//��������
#define		ID_STR_DLG_DEVINFO_ST_COMPANY		39789   //��˾
#define		ID_STR_DLG_DEVINFO_ST_DRIVER		39790	//˾������
#define		ID_STR_DLG_DEVINFO_ST_PHONE			39791	//�绰
#define		ID_STR_DLG_DEVINFO_ST_NATURE		39792	//��������
#define		ID_STR_DLG_DEVINFO_ST_REMARK		39793	//��ע
#define		ID_STR_DLG_DEVINFO_ST_TYPE			39794	//��������
#define		ID_STR_DLG_DEVINFO_ST_CHN_NUM		39795	//ͨ����Ŀ
#define		ID_STR_DLG_DEVINFO_ST_IP			39796	//IP
#define		ID_STR_DLG_DEVINFO_ST_CHN_NAME		39797	//ͨ������
#define		ID_STR_DLG_DEVINFO_ST_DISK		    39798	//����
#define		ID_STR_DLG_DEVINFO_ST_ALL_CAPACITY	39799	//��������
#define		ID_STR_DLG_DEVINFO_ST_SUR_CAPACTTY	39800	//ʣ������
#define		ID_STR_DEV_TYPE_HI3512_SD			39801	//HI3512-Mini-SD
#define		ID_STR_DEV_TYPE_HI3515_DISK			39802	//HI3515-Mini-DISK
#define		ID_STR_DLG_DEVINFO_ST_WAIT_FOR   	39803	//���ڻ�ȡ�豸��Ϣ����ȴ�....
#define		ID_STR_DLG_DEVINFO_ST_CP_SUCC		39804	//��ȡ�豸��Ϣ�ɹ�
#define		ID_STR_DLG_DEVINFO_ST_ERR       	39805	//��ȡ�豸��Ϣʧ�ܣ�����ԭ��
#define		ID_STR_DLG_DEVINFO_BASE          	39806	//����������Ϣ
#define		ID_STR_DLG_DEVINFO              	39807	//�豸��Ϣ

#define		ID_STR_DLG_DEVINFO_DISK_COUNT		39808	//Ӳ����Ŀ
#define		ID_STR_DLG_DEVINFO_3G		        39809	//����ģ��
#define		ID_STR_DLG_DEVINFO_CK_3G_WIFI       39810	//��Ч
#define		ID_STR_DLG_DEVINFO_3G_TYPE   		39811	//ģ������
#define		ID_STR_DLG_DEVINFO_NET_IP       	39812	//�����ַ
#define		ID_STR_DLG_DEVINFO_WIFI		        39813	//WIFIģ��
#define		ID_STR_DLG_DEVINFO_CK_VIDEOLOST		39814	//��Ƶ��ʧ
#define		ID_STR_DLG_DEVINFO_DISK_INFO		39815	//Ӳ����Ϣ
#define		ID_STR_DLG_DEVINFO_RECORD_STATE		39816	//¼��״̬
#define		ID_STR_DLG_DEVINFO_RECORD_TRS_COU	39817	//��Ƶ������Ŀ
#define		ID_STR_DLG_DEVINFO_REFRESH      	39818	//ˢ��
#define     ID_STR_DLG_DEVINFO_VERSION          39819   //�汾
#define     ID_STR_DLG_DEVINFO_YES              39820   //��  
#define     ID_STR_DLG_DEVINFO_NO               39821   //�� 
#define     ID_STR_DLG_DEVINFO_RECORD           39822   //¼��  
#define     ID_STR_DLG_DEVINFO_LOSS             39823   //¼��ʧ
#define     ID_STR_DLG_DEVINFO_3G_WIFI_YES      39824   //ģ����Ч  
#define     ID_STR_DLG_DEVINFO_3G_WIFI_NO       39825   //ģ����Ч

#define     ID_STR_DLG_DEVINFO_CHANNEL_NORMAL			39826   //����ͨ��
#define     ID_STR_DLG_DEVINFO_CHANNEL_UNUSED			39827   //δʹ��ͨ��
#define     ID_STR_DLG_DEVINFO_CHANNEL_RECORDING		39828   //ͨ������¼��
#define     ID_STR_DLG_DEVINFO_CHANNEL_REQUED_RECORD    39829   //ͨ����������¼��
#define     ID_STR_DLG_DEVINFO_CHANNEL_RECORD_ERROR     39830   //ͨ��¼������

#define     ID_STR_DLG_DEV_PROMOTE_TITLE        39900   //�豸����
#define     ID_STR_DLG_DEV_PROMOTE_SUCC         39901   //�������
#define     ID_STR_DLG_DEV_PROMOTE_FAIL         39902   //����ʧ��
#define     ID_STR_DLG_DEV_PROMOTE_FILE_VERSION 39903   //�汾��Ϣ
#define     ID_STR_DLG_DEV_PROMOTE_DEV_TYPE     39904   //�豸����
#define     ID_STR_DLG_DEV_PROMOTE_NOTE         39905   //�����ļ��汾��Ϣ����������ѡ����ȷ�������ļ�
#define     ID_STR_DLG_DEV_PROMOTE_NO           39906   //δ����
#define     ID_STR_DLG_DEV_PROMOTE_DEV_NAME     39907   //�豸����
#define     ID_STR_DLG_DEV_PROMOTE              39908   //����
#define     ID_STR_DLG_DEV_PROMOTE_STATE        39909   //���״̬
#define     ID_STR_DLG_DEV_PROMOTE_FILE         39910   //�����ļ�
#define     ID_STR_DLG_DEV_PROMOTE_LIST         39911   //�豸�����б�
#define     ID_STR_DLG_DEV_PROMOTE_CLEAR        39912  //���
#define     ID_STR_DLG_DEV_PROMOTE_PROCESS      39913  //��������
#define     ID_STR_DLG_DEV_PROMOTE_PROMPT       39914  //��ʾ
#define     ID_STR_DLG_DEV_PROMOTE_TELL         39915  //���豸�������������ļ������������豸�����Ͳ�һ��
#define     ID_STR_DLG_DEV_PROMOTE_FILE_SEL     39916  //��ѡ�������ļ�!
#define     ID_STR_DLG_DEV_PROMOTE_DEV_SEL      39917  //��ѡ��Ҫ�������豸!
#define     ID_STR_DLG_DEV_PROMOTE_STOP         39918  //ȷʵҪֹͣ�豸����?
#define     ID_STR_DLG_DEV_STOP                 39919  //ֹͣ����
#define     ID_STR_DLG_DEV_PROMOTE_FILE_NOTE    39920  //�����ļ��ϴ�״̬:
#define     ID_STR_DLG_DEV_PROMOTE_NOTE_SUCC    39921  //�����ļ��ϴ�״̬:�ϴ������ļ����������ɹ�!
#define     ID_STR_DLG_DEV_PROMOTE_FILE_STOP    39922  //�Ƿ�Ҫֹͣ�ϴ������ļ�?
#define		ID_STR_DLG_DEV_PROMOTE_ERR       	39923	//�豸����ʧ�ܣ�����ԭ��
#define		ID_STR_DLG_DEV_PROMOTE_FILE_STOP_DW 39924	//�����ļ�ֹͣ�ϴ�
#define     ID_STR_DLG_DEV_PROMOTE_FAR_END      39925   //Զ���豸��������
#define     ID_STR_DLG_DEV_UP_VER_SAME_ERROR     39926	//�����ļ��汾���豸�汾��ͬ����ִ����������
#define     ID_STR_DLG_DEV_UP_FILE_ERROR         39927	//�����ļ������ڻ��𻵲��ɶ�
#define     ID_STR_DLG_DEV_DEV_UP_FILE_CRC_ERROR 39928   ///�����ļ�crcУ��ʧ��
#define     ID_STR_DLG_DEV_UP_VER_FAILED_ERROR   39929	//���ܴӵ�ǰ�汾������Ŀ��汾
#define     ID_STR_DLG_DEV_UP_FAILED_ERROR       39930	//����ʧ��
#define     ID_STR_DLG_DEV_UNKNOW_ERROR          39931	//δ֪����
#define     ID_STR_DLG_DEV_PROMOTE_NO_GET        39932   //�޷���ȡ�����ļ�����
#define     ID_STR_DLG_DEV_PROMOTE_TIP           39933   //�����������������ļ�!
#define     ID_STR_DLG_DEV_UP_FILE               39934	//�����ϴ��ļ�
#define     ID_STR_DLG_DEV_UP_CUCC_TIP           39935   //�ɹ��ϴ������ļ����豸,�豸�����������������
#define     ID_STR_DLG_DEV_PROMOTE_READY         39936   //׼������
#define     ID_STR_DLG_DEV_PROMOTE_INFO          39937   //�����ļ�����Ϊ:

#define     ID_STR_DEV_UP_UPGRADING              40001  //��������
#define     ID_STR_ERR_DEV_UP_FILE_WRONG        40002  //�����ļ�����ȷ
#define     ID_STR_ERR_DEV_UP_VER_LOW           40003  //�����ļ��汾����
#define     ID_STR_ERR_DEV_UP_VERIFY_FAILED     40004  //�����ļ�У��ʧ��
#define     ID_STR_ERR_DEV_CHN_NO_EXIST         40005  //ͨ����Ϣ������
#define     ID_STR_ERR_DEV_SNAP_JPG             40006  //ץ��ͼƬʧ��
#define     ID_STR_ERR_DEV_DISK_FULL            40007  //Ӳ�̿ռ䲻��
#define     ID_STR_ERR_SVR_DISK_FULL            40008  //�������ռ䲻��
#define     ID_STR_ERR_SVR_BUSY                 40009  //������æ
#define     ID_STR_ERR_SVR_CREATE_FILE          40010  //�����������ļ�ʧ��
#define     ID_STR_ERR_NOTI_SERVER_NO_EXIST     40011  //֪ͨ������������
#define     ID_STR_ERR_NOTI_SERVER_LINK_FAIL    40012  //֪ͨ����������ʧ��
#define     ID_STR_ERR_MESS_SERVER_NO_START     40013  //����ģ�����û������

#define		ID_STR_DLG_EXPIRED_TIP_USER_RELOGIN	50001	//�û���ɾ����	
#define		ID_STR_DLG_EXPIRED_TIP_USER_EXPIRED	50002	//�û��ѹ��ڣ�
#define		ID_STR_DLG_EXPIRED_TIP_VER_ERR		50003	//�汾��Ϣ��ƥ�䣡	
#define		ID_STR_DLG_EXPIRED_TIP_CMP_ERR		50004	//��˾��Ϣ����
#define		ID_STR_DLG_EXPIRED_TIP_EXIST	    50005	//�û��ѵ�¼!
#define		ID_STR_DLG_EXPIRED_TIP_FULL_ERR		50006	//�������û�����
#define		ID_STR_DLG_EXPIRED_TIP_CNT_ERR		50007	//�޷����ӷ�������
#define     ID_STR_DLG_EXPIRED_TIP_FULL_EMPTY_ERR 50008 //�������û���������Ϣ
#define		ID_STR_DLG_EXPIRED_TIP_USER_DEL		50009	//�û���ɾ����
#define		ID_STR_DLG_EXPIRED_TIP_USER_PRIVILEGE_CHANGE 50010 //�û�Ȩ�޷����仯
#define		ID_STR_DLG_EXPIRED_TIP_SVR_CONFIG_CHANGE 50011 //������������Ϣ�����仯

#define     ID_STR_DLG_PARAMER_TIP_GET          60001  //���ڻ�ȡ�豸������Ϣ�����Ե�......
#define     ID_STR_DLG_PARAMER_GET_FAILT        60002  //��ȡ�豸����ʧ��!
#define     ID_STR_DLG_PARAMER_GET_SUCC         60003  //��ȡ�豸�����ɹ�!
#define     ID_STR_DLG_PARAMER_UP_FILE          60004  //�����ϴ������ļ������Ե�......
#define     ID_STR_DLG_PARAMER_UP_SUCC          60005  //�ϴ������ļ����������ɹ�!
#define     ID_STR_DLG_PARAMER_DOWN_FAILT       60006  //�´����ò����ļ�ʧ��!
#define     ID_STR_DLG_PARAMER_CONFIG           60007  //����
#define     ID_STR_DLG_PARAMER_CONFIG_FINSH     60008  //���������!
#define     ID_STR_DLG_PARAMER_TIP_DOWN         60009  //�����´������ļ�,���Ե�......
#define     ID_STR_DLG_PARAMER_DOWN_STOP        60010  //�´�����ֹͣ!
#define     ID_STR_DLG_PARAMER_UP_STOP          60011  //ֹͣ�ϴ������ļ�!
#define     ID_STR_DLG_PARAMER_STOP_CONFIG      60012  //ֹͣ����
#define     ID_STR_DLG_PARAMER_SAVE_MORE        60013  //���浽����豸
#define     ID_STR_DLG_PARAMER_WINDOW_NAME      60014  //������������
#define     ID_STR_DLG_PARAMER_WARN             60015  //�б�û�п����õ��豸!
#define     ID_STR_DLG_PARAMER_CONFIG_NO        60016  //δ����
#define     ID_STR_DLG_PARAMER_IS_STOP_UP       60017  //�Ƿ�ֹͣ�ϴ������ļ���������?
#define     ID_STR_DLG_PARAMER_IS_STOP_DOWN     60018  //�Ƿ�Ҫֹͣ�´������ļ����豸?
#define     ID_STR_DLG_PARAMER_CONFIG_SUCC      60019  //���óɹ�
#define     ID_STR_DLG_PARAMER_SEL_DEV          60020  //ѡ���豸
#define     ID_STR_DLG_PARAMER_DOWN_SUCC        60021  //�´������ļ����豸�ɹ�!
#define     ID_STR_DLG_PARAMER_IS_GET_PARAMER   60022  //�Ƿ�ֹͣ��ȡ�豸����?
#define     ID_STR_DLG_PARAMER_PARPARE          60023  //׼������
#define     ID_STR_DLG_PARAMER_EXPORT           60024  //��������
#define     ID_STR_DLG_PARAMER_IMPORT           60025  //��������
#define     ID_STR_DLG_PARAMER_UP_STAUE         60026  //�����ļ��ϴ�״̬:
#define     ID_STR_DLG_PARAMER_TIP              60027  //��ʾ:�豸�������޸�,���������豸����!
#define     ID_STR_DLG_PARAMER_STATIC_FILE_CHOSE  60028  //��ѡ�����÷�ʽ
#define     ID_STR_DLG_PARAMER_RADIO_CHANGE       60029  //�����豸�޸��˵Ĳ���
#define     ID_STR_DLG_PARAMER_RADIO_ALL          60030  //�����豸ȫ������
#define     ID_STR_DLG_PARAMER_CHA_UP_SUCC      60031  //�豸�����ı�������Ѿ����!
#define     ID_STR_DLG_PARAMER_ALL_UP_SUCC      60032  //�豸ȫ�������Ѿ��������!
#define     ID_STR_DLG_PARAMER_WARN_DISK        60033  //�˹���Ŀǰֻ֧�ֿ����豸���ݲ�֧��Ӳ�̻��豸!
#define     ID_STR_DLG_PARAMER_INPUT_SUC        60034  //������������ļ��ɹ���
#define     ID_STR_DLG_PARAMER_EXPORT_SUC       60035  //�������������ļ��ɹ���

#define     ID_STR_DLG_CSM_SEND_TIP_PORT_ERROR  61000  //�˿����󣬷�Χ1-65535�����������룡
#define     ID_STR_DLG_CSM_SEND_TIP_IP_ERROR    61001  //IP��ַ���Ϸ������������룡
#define     ID_STR_DLG_CSM_SEND_FRAM            61002  //���������·�
#define     ID_STR_DLG_CSM_SEND_FORMAT          61003  //����ָ��
#define     ID_STR_DLG_CSM_SEND_DEV_NUM         61004  //�豸��
#define     ID_STR_DLG_CSM_SEND_RECEIVE         61005  //����ȷ��
#define     ID_STR_DLG_CSM_SEND_CHECK_RETURN    61006  //�Ƿ�ظ��豸����״̬
#define     ID_STR_DLG_CSM_SEND_PHONE_TIP       61007  //�ֻ���
#define     ID_STR_DLG_CSM_SEND_WARN_PHOME      61008  //�������ֻ���!
#define     ID_STR_DLG_CSM_SEND_WARN_NUM        61009  //�������豸��!
#define     ID_STR_DLG_CSM_SEND_WARN_SIM        61010  //�豸SIM��Ϊ�գ��������·���������!
#define     ID_STR_DLG_CSM_SEND_MOD_DEV         61011  //�޸��豸��
#define     ID_STR_DLG_CSM_SEND_GET_STATUS      61012  //��ȡ�豸״̬
#define     ID_STR_DLG_CSM_SEND_MOD_CENTER_IP   61013  //�޸�����IP
#define     ID_STR_DLG_CSM_SEND_3G_BH           61014  //3g����
#define     ID_STR_DLG_CSM_SEND_CONTENT         61015  //��ǰ�·�:
#define     ID_STR_DLG_CMS_SEND_ADD_DEV         61016  //�豸�б�û���·��ĳ�����������!
#define     ID_STR_DLG_CMS_SEND_CONTENT         61017  //�·�����:
#define     ID_STR_DLG_CMS_SEND_DEV_SIM         61018  //�豸Sim��:
#define     ID_STR_DLG_CMS_SEND_SUCC            61019  //������Ϣ�·��ɹ�
#define     ID_STR_DLG_CMS_SEND_FAIL            61020  //������Ϣ�·�ʧ��
#define     ID_STR_DLG_CMS_SEND_IS_HAVE         61021  //�벻Ҫ�ظ������Ӹó���
#define     ID_STR_DLG_CMS_SEND_OPEN            61022  //����
#define     ID_STR_DLG_CMS_SEND_CLOSE           61023  //�ر�
#define     ID_STR_DLG_CMS_SEND_CLOSE_DISPLAY   61024  //�ر���ʱ
#define     ID_STR_DLG_CMS_SEND_REBOOT_DISPLAY  61025  //������ʱ
#define     ID_STR_DLG_CMS_SEND_PORT            61026  //�˿�
#define     ID_STR_DLG_CMS_SEND_ENABLE_SEND     61027  //���ֻ������·�
#define     ID_STR_DLG_CMS_SEND_TELL            61028  //�·�˵��
#define     ID_STR_DLG_CMS_SEMD_1               61029  //��ʽһ:ʹ�ñ�ƽ̨�·�
#define     ID_STR_DLG_CMS_SEND_2               61030  //��ʽ��:�û��ɱ༭�����·�
#define     ID_STR_DLG_CMD_SEND_3G_STATUS       61031  //3G״̬

#define     ID_STR_DLG_CMS_STATISTIC_DEV_GROUP  62000  //������
#define     ID_STR_DLG_CMS_STATISTIC_DEVGROUP   62001  //����/������
#define     ID_STR_DLG_CMS_STAITSTIC_IP_PORT    62002  //�ն�IP/�˿�
#define     ID_STR_DLG_CMS_STAITSTIC_ONLINE     62003  //��������
#define     ID_STR_DLG_CMS_STAITSTIC_OFFLINE    62004  //��������
#define     ID_STR_DLG_CMS_STAITSTIC_LINE_ON_OFF    62005  //����������
#define     ID_STR_DLG_CMS_STAITSTIC_ACC_ON     62006  //ACC����
#define     ID_STR_DLG_CMS_STAITSTIC_ACC_OFF    62007  //ACC�ر�
#define     ID_STR_DLG_CMS_STAITSTIC_ACC_ON_OFF 62008  //ACC���ر�
#define     ID_STR_DLG_CMS_STATICTIS_BTN_NUM    62009  //��ť���
#define     ID_STR_DLG_CMS_STATICTIS_OTHER_NAME 62010  //����
#define     ID_STR_DLG_CMS_STATISTIC_WARN_DOOR  62011  //������
#define     ID_STR_DLG_CMS_STATISTIC_EXCEPT_DES 62012  //�쳣����
#define     ID_STR_DLG_CMS_STATISTIC_DISK_NUM   62013  //Ӳ�̺�
#define     ID_STR_DLG_CMS_STATISTIC_ERR_DES    62014  //��������
#define     ID_STR_DLG_CMS_STATISTIC_WARN_CA    62015  //�������
#define     ID_STR_DLG_CMS_STATISTIC_FENCE_NUM  62016  //Χ����
#define     ID_STR_DLG_CMS_STATISTIC_WARN_NUM   62017  //�������
#define     ID_STR_DLG_CMS_STATISTIC_WARN_SOURCE     62018  //����Դ
#define     ID_STR_DLG_CMS_STATISTIC_WARN_NAME       62019  //��������
#define     ID_STR_DLG_CMS_STATISTIC_WARN_SPEED      62020  //�����ٶ�
#define     ID_STR_DLG_CMS_STATISTIC_WARN_MIN_SPEED  62021  //����ٶ�
#define     ID_STR_DLG_CMS_STATISTIC_WARN_MAX_SPEED  62022  //����ٶ�

#define     ID_STR_DLG_CMS_STATISTIC_DEV_ON_OFF_REPORT  62023 //���������߱���
#define     ID_STR_DLG_CMS_STATISTIC_DEV_ON_OFF_STAITS  62024 //����������ͳ��
#define     ID_STR_DLG_CMS_STATISTIC_ACC_REPORT         62025 //ACC����
#define     ID_STR_DLG_CMS_STATISTIC_ACC_STATISTIC      62026 //ACCͳ��
#define     ID_STR_DLG_CMS_STATISTIC_VIDEO_REPORT       62027 //��Ƶ����
#define     ID_STR_DLG_CMS_STATISTIC_VIDEO_NO_SIGNAL    62028 //��Ƶ���ź�
#define     ID_STR_DLG_CMS_STATISTIC_VIDEO_HIDE         62029 //��Ƶ�ڵ�
#define     ID_STR_DLG_CMS_STATISTIC_SPEED_REPORT       62030 //�ٶȱ���
#define     ID_STR_DLG_CMS_STATISTIC_SPEED_CURVE        62031 //�ٶ�����
#define     ID_STR_DLG_CMS_STATISTIC_OVER_SPEED_REPORT  62032 //���ٱ���
#define     ID_STR_DLG_CMS_STATISTIC_ORTHER_REPORT_STAT 62033 //��������ͳ��
#define     ID_STR_DLG_CMS_STATISTIC_CUSTOM_WARN        62034 //�Զ��屨��
#define     ID_STR_DLG_CMS_STATISTIC_EME_BUT_WARN       62035 //������ť����
#define     ID_STR_DLG_CMS_STATISTIC_SHOCK_WARN         62036 //�𶯱���
#define     ID_STR_DLG_CMS_STATISTIC_ILLEAGL_OPEN_WARN  62037 //�Ƿ����ű���
#define     ID_STR_DLG_CMS_STATISTIC_THREE_ERR_WARN     62038 //����������󱨾�
#define     ID_STR_DLG_CMS_STATISTIC_DISK_ERR_WARN      62039 //Ӳ�̴��󱨾�
#define     ID_STR_DLG_CMS_STATISTIC_ABNORM_ONOFF_WARN  62040 //�쳣�����ű���
#define     ID_STR_DLG_CMS_STATISTIC_CROSS_WARN         62041 //Խ�籨��
#define     ID_STR_DLG_CMS_STATISTIC_ABNORMAL_FIRE_WARN 62042 //�Ƿ���𱨾�
#define     ID_STR_DLG_CMS_STATISTIC_SET_DATE_TIP       62043 //��ʾ:֧�ֲ�ѯĳһ���µ���Ϣ,��ѯ�Ľ��Ϊ��ʼʱ����Ǹ��µ�ʱ����ڵ�����!
#define     ID_STR_DLG_CMS_STATISTIC_TIP_DATE_TELL      62044 //��ʾ:֧�ֲ�ѯĳһ���µ���Ϣ
#define     ID_STR_DLG_CMS_STATISTIC_TIP_DATE_TELL_WARN 62045 //,���β�ѯ���Ϊ%d�·��ڵĲ�ѯʱ����ڵ�����!;
#define     ID_STR_DLG_CMS_STATISTIC_VEHICLE_POS        62046 //�鿴����λ��



#define     ID_STR_CMS_BRAKE                        63000 //ɲ��
#define     ID_STR_CMS_LEFT                         63001 //��ת
#define     ID_STR_CMS_RIGHT                        63002 //��ת
#define     ID_STR_CMS_POSITIVE                     63003 //ת��
#define     ID_STR_CMS_REVERSE                      63004 //��ת
#define		ID_STR_DESC_PARK_LAST_TIME		        63005 //ͣ��ʱ����
#define		ID_STR_DESC_PARK_SETUP_TIME		        63006 //�趨ʱ����
#define     ID_STR_CMS_GPS_VALID                    63007 //GPS��λ��Ч
#define     ID_STR_CMS_GPS_INVALID                  63008 //GPS��λ��Ч
#define     ID_STR_CMS_GPS_ANTENNA_VALID            63009 //GPS������Ч
#define     ID_STR_CMS_GPS_ANTENNA_NORMAL           63010 //GPS���ߴ���
#define     ID_STR_CMS_GPS_ANTENNA_INVALID          63011 //GPS���߲�����
#define     ID_STR_CMS_GPS_DISK_NOT_EXIST           63012 //Ӳ�̲�����
#define     ID_STR_CMS_GPS_DISK_EXIST               63013 //Ӳ�̴���
#define     ID_STR_CMS_GPS_DISK_DISCONNECT_POWER    63014 //Ӳ�̶ϵ�
#define     ID_STR_CMS_3G_NOT_EXIST                 63015 //3Gģ�鲻����
#define     ID_STR_CMS_3G_NO_SIGNAL                 63016 //3G���ź�
#define     ID_STR_CMS_3G_SIGNAL_POOR               63017 //3G�źŲ�
#define     ID_STR_CMS_3G_SIGNAL_GENERAL            63018 //3G�ź�һ��
#define     ID_STR_CMS_3G_SIGNAL_GOOD               63019 //3G�źź�
#define     ID_STR_CMS_3G_SIGNAL_EXCELLENT          63020 //3G�ź���
#define     ID_STR_CMS_SFM_TIP                      63021 //(%dСʱ%d��%d��)
#define     ID_STR_CMS_FM_TIP                       63022 //(%d��%d��)
#define     ID_STR_CMS_M_TIP                        63023 //(%d��)
#define     ID_STR_CMS_DEVICE_STATIC                63024 //ͣ��
#define     ID_STR_CMS_DEVICE_OVER_SPEED            63025 //����
#define     ID_STR_CMS_3G_SIGNAL_CLOSE		        63026 //3G���ܹر�
#define     ID_STR_CMS_3G_SIM_NOT_EXIST		        63027 //SIM��������
#define     ID_STR_CMS_GPS_DISK						63028 //Ӳ��
#define     ID_STR_CMS_GPS_NOT_EXIST				63029 //������
#define     ID_STR_CMS_GPS_EXIST					63030 //����
#define     ID_STR_CMS_GPS_DISCONNECT_POWER			63031 //�ϵ�
#define     ID_STR_CMS_3G_SIGNAL_WEAK		        63032 //�ź���
#define     ID_STR_CMS_GPS_SD						63033 //SD��
#define     ID_STR_CMS_GPS_SSD						63034 //SSD

#define     ID_STR_UP_3G_INTERVAL              64000 //�ϱ��������
#define     ID_STR_UP_3G_INTERVAL_TIME_FW      64001 //(3-3600��)
#define     ID_STR_UP_3G_INTERVAL_WARN_EMPTY   64002 //Gps�ϱ���ʱ��������Ϊ��!
#define     ID_STR_UP_3G_INTERVAL_BETWEEN      64003 //�ϱ�Gpsʱ��������%d-%d֮��!
#define     ID_STR_UP_3G_INTERVAL_SET          64004 //GPS�ϱ��������
#define     ID_STR_UP_GPS_INTERVAL_FAIL        64005 //GPS�ϱ��������ʧ��
#define     ID_STR_UP_GPS_INTERVAL_SUCC        64006 //GPS�ϱ�������óɹ�
#define     ID_STR_UP_GPS_INTERVAL_TIP         64007 //GPS�ϱ����:
#define     ID_STR_UP_GPS_UNIT                 64008 //��

#define     ID_STR_DLG_STATISTIC_BUT_BIG         65000  //�Ŵ�
#define     ID_STR_DLG_STATISTIC_BUT_SMALL       65001  //��С
#define     ID_STR_DLG_STATISTIC_BUT_MOVE_LEFT   65002  //���ƶ�
#define     ID_STR_DLG_STATISTIC_BUT_MOVE_RIGHT  65003  //���ƶ�
#define     ID_STR_DLG_STATISTIC_BUT_PRINT       65004  //��ӡ
#define     ID_STR_DLG_STATISTIC_STATIC_TEEL_TIP 65005  //------->��ܰ��ʾ�����ڲ�ѯ�����ݵ�Ƚ϶�,������Ҫ��ʱ��!
#define     ID_STR_DLG_STATISTIC_BUT_QUERY       65006  //��ѯ
#define     ID_STR_CMS_STATTISTIC_SPEED_CURVE    65007 //���������ٶ����ߣ�ȷ��Ҫ���²�ѯ�ٶ�����?
#define     ID_STR_CMS_STATISTIC_RE_QUERY        65008 //���²�ѯ
#define     ID_STR_CMS_STATISTIC_TIP_FOR         65009 //"�϶����ɷŴ����ߡ�Ҳ����ͨ����껬����������";
#define     ID_STR_CMS_STATISTIC_SPEEDTIME_TIP   65010 //�ٶ�����

#define     ID_STR_DLG_STATISTIC_SPEED_CURVE_PAGE_SET   65011  //ֽ������
#define     ID_STR_DLG_STATISTIC_STATIC_SET             65012  //���ô�ӡ���
#define     ID_STR_DLG_STATISTIC_RADIO_HENG             65013  //�����ӡ
#define     ID_STR_DLG_STATISTIC_RADIO_ZONG             65014  //�����ӡ
#define     ID_STR_DLG_STATISTIC_BTN_SET                65015  //����
#define     ID_STR_DLG_STATISTIC_TELL_TIP               65016  //�����ݿɴ�ӡ   

#define     ID_STR_DLG_CHANNEL_GROUP_WARN_EMPTY  66000    //�������Ʋ���Ϊ��!
#define     ID_STR_DLG_CHANNEL_GROUP_WARN_HAVE   66001    //���������Ѿ�����!
#define     ID_STR_DLG_CHANNEL_GROUP_ADD         66002    //���ӷ���
#define     ID_STR_DLG_CHANNEL_GROUP_NAME        66003    //��������
#define     ID_STR_DLG_CHANNEL_GROUP_TIP         66004    //��ʾ--->�Ҽ�����ͨ������
#define     ID_STR_DLG_CHANNEL_GROUP_CONFIG      66005    //��������
#define     ID_STR_DLG_CHANNEL_GROUP_DEV_LIST    66006    //�豸�б�
#define     ID_STR_DLG_CHANNEL_GROUP_TO          66007    //ͨ������
#define     ID_STR_DLG_CHANNEL_GROUP_ADD_WARN    66008   //�����ӷ���!  
#define     ID_STR_DLG_CHANNEL_GROUP_DEV_SL_WARN 66009   //��ѡ���豸��ͨ��!
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_WARN    66010   //�޿�ɾ���ķ����ͨ��!
#define     ID_STR_DLG_CHANNEL_GROUP_SEL_WARN    66011   //�����ұߵ�����ѡ��һ�������ͨ��!
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_GROUP   66012   //ɾ������
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_DEV     66013   //ɾ���豸
#define     ID_STR_DLG_CHANNEL_GROUP_POLLING     66014   //��ѯ����%s������ѯ���Ƿ�Ҫɾ��
#define     ID_STR_DLG_CHANNEL_GROUP_DEL_TIP     66015   //�Ƿ�Ҫɾ����ѯ����%s!
#define     ID_STR_DLG_CHANNEL_GROUP_POLL_WND    66016   //��ѯ����%s���ڴ���%d����ѯ!
#define     ID_STR_DLG_CHANNEL_TELL_TIP          66017   //��ܰ��ʾ:�����������ظ�,ÿ�������µ��豸ͨ�����ظ�!
#define		ID_STR_DLG_CHANNEL_GROUP_ITEM_TIP	 66018	 //��ܰ��ʾ:\t\n�϶��ڵ㵽��Ƶ���ڿ�����ѯ.
#define		ID_STR_DLG_CHANNEL_GROUP_ITEM_TIP2	 66019	 //�϶��ڵ㵽��Ƶ���ڿ�����ѯ.

#define     ID_STR_DLG_MOTION_CONFIG             67000   //�ƶ��������
#define     ID_STR_DLG_MOTION_ENABLE             67001   //ʹ��
#define     ID_STR_DLG_MOTION_OPEN               67002   //��
#define     ID_STR_DLG_MOTION_CLOSE              67003   //��
#define     ID_STR_DLG_MOTION_SENEITIVE          67004   //������
#define     ID_STR_DLG_MOTION_LOW                67005   //��
#define     ID_STR_DLG_MOTION_MIDDLE             67006   //��
#define     ID_STR_DLG_MOTION_HIGH               67007   //��
#define     ID_STR_DLG_MOTION_TOP_TIP            67008   //��������϶�,ѡ��Ҫ���õķ�������!
#define     ID_STR_DLG_MOTION_GET_P_SUCC         67009   //ץ��ͼƬ�ɹ�! 
#define     ID_STR_DLG_MOTION_GETTING_P_NOW      67010   //���ڻ�ȡץ��ͼƬ,���Ե�......
#define     ID_STR_DLG_MOTION_CONFIG_STOP        67011   //�ƶ��������ֹͣ!
#define     ID_STR_DLG_MOTION_GET_INFO           67012   //���ڻ�ȡ�ƶ������Ϣ����ȴ�......
#define     ID_STR_DLG_MOTION_GET_INFO_SUCC      67013   //��ȡ�ƶ������Ϣ�ɹ�!
#define     ID_STR_DLG_MOTION_CONFIGING_NOW      67014   //���������ƶ������Ϣ����ȴ�......
#define     ID_STR_DLG_MOTION_CONFIG_SUCC        67015   //�ƶ���������óɹ�!
#define     ID_STR_DLG_MOTION_CLEAR              67016   //������
#define     ID_STR_DLG_MOTION_GET_INFO_FAILT     67017   //��ȡ�ƶ������Ϣʧ��!

#define     ID_STR_DLG_3G_FLOW_STATISTIC         68000   //3G����ͳ��
#define     ID_STR_DLG_3G_FLOW_CONFIG            68001   //3G��������
#define     ID_STR_DLG_3G_FLOW_PAY_SYSTEM        68002   //����������������Ӫ�̵ļƷ�ϵͳΪ׼
#define     ID_STR_DLG_3G_FLOW_CURRENT_USE       68003   //��ǰ��������
#define     ID_STR_DLG_3G_FLOW_CURRENT_MONTH     68004   //������������
#define     ID_STR_DLG_3G_FLOW_DAY_LIMIT         68005   //����������
#define     ID_STR_DLG_3G_FLOW_MONTH_LIMIT       68006   //����������
#define     ID_STR_DLG_3G_FLOW_USED_STATUS       68007   //GPRS/3Gʹ��״̬
#define     ID_STR_DLG_3G_FLOW_TODAY_USE         68008   //��������
#define     ID_STR_DLG_3G_FLOW_UNIT              68009   //��
#define     ID_STR_DLG_3G_FLOW_CURRENT_MONTH_USE 68010   //��������
#define     ID_STR_DLG_3G_FLOW_CURRENT_DAY_USE   68011   //����ʣ��
#define     ID_STR_DLG_3G_FLOW_CURRENT_LIMIT     68012   //�����޶�
#define     ID_STR_DLG_3G_FLOW_CON_PAY_DAY       68013   //�ݽ�����
#define     ID_STR_DLG_3G_FLOW_SET               68014   //��������
#define     ID_STR_DLG_3G_FLOW_MONTH_PACKAGE     68015   //ÿ���ײ��޶�
#define     ID_STR_DLG_3G_FLOW_MONTH_USE_TELL    68016   //ÿ����������
#define     ID_STR_DLG_3G_FLOW_PAY_DAY           68017   //������
#define     ID_STR_DLG_3G_FLOW_DAY_TELL          68018   //ÿ������
#define     ID_STR_DLG_3G_FLOW_MONTOR_ENABLE     68019   //�����������
#define     ID_STR_DLG_3G_FLOW_ADJUST            68020   //����У��
#define     ID_STR_DLG_3G_FLOW_CLEAR_DATA        68021   //���ͳ������
#define     ID_STR_DLG_3G_FLOW_GET_3G_INFO_SUCC  68022   //��ȡ�豸3G��Ϣ�ɹ�!
#define     ID_STR_DLG_3G_FLOW_GET_3G_INFO_FAIL  68023   //��ȡ�豸3G��Ϣʧ��!ԭ��:
#define     ID_STR_DLG_3G_FLOW_GET_3G_INFO_WAIT  68024   //���ڻ�ȡ�豸3G��Ϣ����ȴ�......
#define     ID_STR_DLG_3G_FLOW_SET_3G_INFO_SUCC  68025   //�����豸3G��Ϣ���óɹ�!
#define     ID_STR_DLG_3G_FLOW_SET_3G_INFO_FAIL  68026   //�����豸3G��Ϣʧ��!ԭ��:
#define     ID_STR_DLG_3G_FLOW_MONTH_BETWEEN_TIP 68027   //�½��ս���1��31֮��!����������! 
#define     ID_STR_DLG_3G_FLOW_TH                68028   //��
#define     ID_STR_DLG_3G_FLOW_DAY               68029   //��  
#define     ID_STR_DLG_3G_FLOW_NO_STATISTIC_DEV  68030   //û�п�ͳ�Ƶ����߳���!
#define     ID_SRE_DLG_3G_FLOW_ADJUST_SUCC       68031   //У�����óɹ�
#define     ID_SRE_DLG_3G_FLOW_ADJUST_FAIL       68032   //У�����óɹ�
#define     ID_SRE_DLG_3G_FLOW_ADJUST            68033   //У��
#define     ID_SRE_DLG_3G_FLOW_ADJUST_STOP       68034   //ֹͣУ��
#define     ID_SRE_DLG_3G_FLOW_ADJUST_VALUE_WARN 68035   //������У��ֵ����0-10240֮��!
#define     ID_STR_DLG_3G_FLOW_MANUAL            68036   //�ֶ�У��
#define		ID_STR_DLG_3G_FLOW_DAY_REMINDE			 68037	 //����������
#define		ID_STR_DLG_3G_FLOW_OPEN_DAY_REMINDE		 68038	 //����ÿ������
#define		ID_STR_DLG_3G_FLOW_OPEN_MONTH_REMINDE	68039	//����ÿ������
#define		ID_STR_DLG_3G_FLOW_MONTH_REMINDE			 68040	 //����������
#define		ID_STR_DLG_3G_FLOW_REMINDE				68041		//��������
#define     ID_STR_DLG_3G_FLOW_MONTH_FLOW_TIP	68042   //ÿ���ײ��޶����0��1024000֮��!����������! 
#define     ID_STR_DLG_3G_FLOW_DALY_FLOW_TIP	68043   //ÿ���޶����0��1024000֮��!����������! 
#define     ID_STR_DLG_3G_FLOW_DAY_FLOW_REMIND_TIP	68044   //ÿ���������ѽ���0��99֮��!����������! 
#define     ID_STR_DLG_3G_FLOW_MONTH_FLOW_REMIND_TIP	68045   //ÿ���������ѽ���0��99֮��!����������! 

#define     ID_STR_DLG_ALARM_SHIELD              69000   //������������
#define     ID_STR_DLG_ALARM_SHIELD_CONFIG_SUC   69001   //�����������óɹ�!
#define     ID_STR_DLG_ALARM_SHIELD_CONFIG_FIAL  69002   //������������ʧ��!

#define     ID_STR_MY_MAP                        69100   //�ҵĵ�ͼ
#define     ID_STR_MY_MAP_NAME                   69101   //����
#define     ID_STR_MY_MAP_TYPE                   69102   //����
#define     ID_STR_MY_MAP_DD				     69103   //�ص� 
#define     ID_STR_MY_MAP_MENU_MODIFY_DEV        69104   //�޸Ĺ����豸
#define     ID_STR_MY_MAP_MENU_MODIFY_FENCE      69105   //�޸�����
#define     ID_STR_MY_MAP_MENU_ADD_FENCE         69106   //��������
#define     ID_STR_MY_MAP_MENU_DEL_FENCE         69107   //ɾ������
#define		ID_STR_MY_MAP_MENU_DEL_ALL			 69108	 //ɾ�����е�����
#define		ID_STR_MY_MAP_POINT					 69109	 //��
#define		ID_STR_MY_MAP_LINE					 69110	 //��
#define		ID_STR_MY_MAP_MARKE					 69111	 //��


#define     ID_STR_DLG_ALARM_IO_TIP              69200   //%s����
#define     ID_STR_DLG_IO_ALAEM                  69201   //IO����
#define     ID_STR_DLG_MOTION_UNIT_DC            69202  //���϶�
#define     ID_STR_DLG_PANE_MAP_ALARM_POINT      69203  //������



#define		ID_STR_DLG_TOP_TAG_BTN_MAN			 69300	 //��ҳ
#define		ID_STR_DLG_TOP_TAG_BTN_TRACK_BACK	 69301	 //�켣�ط�
#define		ID_STR_DLG_TOP_TAG_BTN_FULL_SRCEEN	 69302	 //ȫ��
#define		ID_STR_DLG_TOP_TAG_BTN_VIDEO_WND	 69303	 //��Ƶ
#define		ID_STR_DLG_TOP_TAG_BTN_REBOOT		 69304	 //ע��
#define		ID_STR_DLG_TOP_TAG_BTN_MIN			 69305	 //��С��
#define		ID_STR_DLG_TOP_TAG_BTN_EXIT			 69306	 //�˳�
#define		ID_STR_DLG_TOP_TAG_BTN_REBOOT_MSG	 69307	 //ȷ��Ҫ�л��û���¼?
#define		ID_STR_DLG_TOP_TAG_BTN_EXIT_MSG		 69308	 //ȷ��Ҫ�˳�ϵͳ?
#define		ID_STR_DLG_TOP_TAG_BTN_MAP			 69309	 //���ӵ�ͼ
#define		ID_STR_DLG_TOP_TAG_BTN_VIDEO		 69310	 //ʵʱԤ��
#define		ID_STR_DLG_TOP_TAG_BTN_RECORD_BACK	 69311	 //¼���ѯ
#define		ID_STR_DLG_TOP_TAG_BTN_REPORT		 69312	 //����ͳ��
#define		ID_STR_DLG_TOP_TAG_BTN_OTHER		 69313	 //����Ӧ��
#define		ID_STR_PTZ_SPEED					 69314	 //- �ٶ� +
#define		ID_STR_DLG_TOP_TAG_BTN_REPOSITION_MAX		69315	 //���
#define		ID_STR_DLG_TOP_TAG_BTN_REPOSITION_NORMAL	 69316	 //��ԭ
#define		ID_STR_DLG_OHTER_SET_BTN_WEB_CLIENT	 69317	 //������ѯ

#define		ID_STR_DLG_MARKER_POINT_TITLE		69401	//�����Զ����
#define		ID_STR_DLG_MARKER_POINT_ST_TYPE		69402	//����
#define		ID_STR_DLG_MARKER_POINT_ST_JINGDU	69403	//����
#define		ID_STR_DLG_MARKER_POINT_ST_WEIDU	69404	//γ��
#define		ID_STR_DLG_MARKER_POINT_ST_NAME		69405	//����
#define		ID_STR_DLG_MARKER_POINT_ST_REMARKS	69406	//����
#define		ID_STR_DLG_MARKER_POINT_NAME_EMPTY	69407	//���Ʋ���Ϊ��
#define		ID_STR_DLG_MARKER_POINT_ST_SHARE	69408	//����
#define		ID_STR_DLG_MARKER_POINT_CHK_SHARE	69409	//���������û��鿴
#define		ID_STR_DLG_MARKER_RECT_TITLE		69410	//���Ӿ���
#define		ID_STR_DLG_MARKER_POLYGON_TITLE		69411	//���Ӷ����
#define		ID_STR_DLG_MARKER_POINT_ST_QIDIAN	69412	//���
#define		ID_STR_DLG_MARKER_POINT_ST_ZHONGDIAN	69413	//�յ�
#define		ID_STR_DLG_MARKER_LINE_TITLE		69414	//������·
#define		ID_STR_DLG_MARKER_ADD_FAILED		69415	//����ʧ��

#define		ID_STR_MARKER_TYPE_CAMP				69419	//Ӫ��
#define		ID_STR_MARKER_TYPE_VILLAGE			69420	//��ׯ
#define		ID_STR_MARKER_TYPE_FACTORY			69421	//����
#define		ID_STR_MARKER_TYPE_GONGDI			69422	//����
#define		ID_STR_MARKER_TYPE_WAREHOURSE		69423	//�ֿ�
#define		ID_STR_MARKER_TYPE_PIER				69424	//��ͷ
#define		ID_STR_MARKER_TYPE_WULIU			69425	//����԰
#define		ID_STR_MARKER_TYPE_SHOUFEI			69426	//�շ�վ
#define		ID_STR_MARKER_TYPE_TRACKPOINT		69427	//���ٵ�
#define		ID_STR_MARKER_TYPE_OTHER			69428	//����
#define		ID_STR_DEV_MOBLIE					69429	//�ֻ�
#define		ID_STR_MAP_CONFIG					69430	//��ͼ����
#define		ID_STR_MAP_CONFIG_ZOOM				69431	//���ż���
#define		ID_STR_MAP_CONFIG_SUC				69432	//��ͼ���ĵ����óɹ�
#define		ID_STR_MAP_CONFIG_CENTER_SURE		69433	//ȷ��Ҫ�ѵ�ǰ��ͼλ������ΪĬ�ϵ�ͼ����λ����

#define		ID_STR_PANE_MAP_SEARCH_PARTNER		69500	//�������Ѻ���Դ
#define		ID_STR_PANE_MAP_SEARCH_RES			69501	//������Դ
#define		ID_STR_PANE_MAP_SEARCH_DISTANCE		69502	//����(��)
#define		ID_STR_PANE_MAP_SEARCH_RADIUS		69503	//�����뾶
#define		ID_STR_PANE_MAP_SEARCH_MAN_NUM		69504	//�������
#define		ID_STR_PANE_MAP_SEARCH_EUQ_NUM		69505	//���������
#define		ID_STR_PANE_MAP_SEARCH_SEND_MSG		69506	//���Ͷ���
#define		ID_STR_PANE_MAP_SEARCH_SEND_CMD		69507	//���͵�������
#define		ID_STR_PANE_MAP_SEARCH				69508	//��������
#define		ID_STR_PANE_MAP_SEARCH_PIC			69509	//��
#define		ID_STR_PANE_MAP_SEARCH_MI			69510	//��
#define		ID_STR_PANE_MAP_SEARCH_MAN			69511	//���
#define		ID_STR_PANE_MAP_SEARCH_EUQ			69512	//�����
#define		ID_STR_PANE_SEND_CMD_SENDING		69513	//������...
#define		ID_STR_PANE_SEND_CMD_SEND_SUC		69514	//�ɹ�
#define		ID_STR_PANE_SEND_CMD_SEND_FAILED	69515	//ʧ��
#define		ID_STR_PANE_SEND_CMD_SEND_STATUS	69516	//����״̬
#define		ID_STR_PANE_ALARM_TYPE				69517	//��������
#define		ID_STR_PANE_ALARM_MAN				69518	//������Ա
#define		ID_STR_PANE_ALARM_IMAGE_SHOW		69519	//�鿴����ͼƬ
#define		ID_STR_PANE_ALARM_IMAGE_SHOW_FAIL		69520	//��ȡͼƬʧ��.
#define		ID_STR_PANE_ALARM_IMAGE_SHOW_LOADING		69521	//���ڼ���ͼƬ...



#define		ID_STR_WEEK_1						70000	//һ
#define		ID_STR_WEEK_2						70001	//��
#define		ID_STR_WEEK_3						70002	//��
#define		ID_STR_WEEK_4						70003	//��
#define		ID_STR_WEEK_5						70004	//��
#define		ID_STR_WEEK_6						70005	//��
#define		ID_STR_WEEK_7						70006	//��

#define		ID_STR_CFG_GET_SUC					70050	//��ȡ�����ɹ�.
#define		ID_STR_CFG_GET_FAILED				70051	//��ȡ����ʧ��.
#define		ID_STR_CFG_SET_SUC					70052	//���ò����ɹ�.
#define		ID_STR_CFG_SET_FAILED				70053	//���ò���ʧ��.
#define		ID_STR_CFG_SET_ING					70054	//���ò�����...
#define		ID_STR_CFG_GET_ING					70055	//��ȡ������...

#define		ID_STR_CFG_AUDIO_INPUT_TITLE			70100	//��Ƶ����
#define		ID_STR_CFG_AUDIO_INPUT_MIC_IN			70101	//�������
#define		ID_STR_CFG_AUDIO_INPUT_LINE_IN			70102	//��������

#define		ID_STR_CFG_AUDIO_CAP_TITLE				70120	//��Ƶ���
#define		ID_STR_CFG_AUDIO_CAPTURE				70121	//�ɼ���Ƶ
#define		ID_STR_CFG_AUDIO_CAP_FORMAT				70122	//��Ƶ��ʽ

#define		ID_STR_CFG_VIDEO_TITLE					70140	//��Ƶ����
#define		ID_STR_CFG_VIDEO_VBR					70141	//�ɱ�����
#define		ID_STR_CFG_VIDEO_CBR					70142	//�̶�����
#define		ID_STR_CFG_VIDEO_CODE_RATE				70143	//����
#define		ID_STR_CFG_VIDEO_I_FRAME_SPACE			70144	//��֡���
#define		ID_STR_CFG_VIDEO_FRAME_RATE				70145	//֡��
#define		ID_STR_CFG_VIDEO_CODE_CONTROL			70146	//��Ƶ�������
#define		ID_STR_CFG_VIDEO_CODE_QUALITY			70147	//��Ƶ��������
#define		ID_STR_CFG_VIDEO_QUALITY_TIP			70148	//(ֵԽС��ͼ������Խ�ã��������Ʒ���Խ��)


#define		ID_STR_CFG_PTZ_TITLE					70160	//��̨����
#define		ID_STR_CFG_PTZ_CODE						70161	//Э����
#define		ID_STR_CFG_PTZ_PROTOCOL					70162	//Э��
#define		ID_STR_CFG_PTZ_BAUDRATE					70163	//������
#define		ID_STR_CFG_PTZ_DATA_BIT					70164	//����λ
#define		ID_STR_CFG_PTZ_STOP_BIT					70165	//ֹͣλ
#define		ID_STR_CFG_PTZ_CHECK_BIT				70166	//У��
#define		ID_STR_CFG_PTZ_CHECK_NONE				70167	//��
#define		ID_STR_CFG_PTZ_CHECK_ODD				70168	//��У��
#define		ID_STR_CFG_PTZ_CHECK_EVEN				70169	//żУ��


#endif